test-config:
  comparison-config:
    type: AllCloseHw
    atol: 0.01
    rtol: 0.15
    check_pcc: 0.99
    check_pct: 0.80
    verbosity: Concise
    overrides: # Either have this overrides section, or it cannot be empty.
      determinism_test:
        type: Exact
        lhs_header : Initial Tile
        rhs_header : Current Tile
  stimulus-config:
    type: Uniform
    uniform_lower_bound: -1.0
    uniform_upper_bound: 1.0
