test-config:
  comparison-config:
    type: AllCloseHw
    atol: 0.01
    rtol: 0.15
    check_pct: 0.0
    check_pcc: 0.98
    #verbosity: Verbose
    verbosity: Concise
    overrides: # Either have this overrides section, or it cannot be empty.
      determinism_test:
        type: Exact
        lhs_header : Initial Tile
        rhs_header : Current Tile
        #verbosity: AllFails
    #   output0: 
    #     type: AllCloseHw
    #     atol: 0.005
    #     rtol: 0.10
    #     check_pcc: 0.99
    #     verbosity: Concise
    #     check_tile_rows_range: [1,1]   # specifies 1-based inclusive range of rows within a tile that 
    #                            # will be checked, rows outside of the range will be ignored
    #     check_tile_col_range: [1,32]  # same as for the rows
    #   string_tag: 
    #     type: AllCloseHw
    #     atol: 0.005
    #     rtol: 0.10
    #     check_pcc: 0.99
    #     verbosity: Concise
  stimulus-config:
    type: Uniform
    uniform_lower_bound: 0.001
    uniform_upper_bound: 2.0
    #type: Constant
    #constant_value: 1.0
    # overrides:  # Either have this overrides section, or it cannot be empty.
    #   input0: 
    #     type: Uniform
    #     uniform_lower_bound: 0.001
    #     uniform_upper_bound: 1.000
    #     set_tile_rows: [1,1]   # specifies 1-based inclusive range of rows within a tile that 
    #                            # will be initialized, rows outside of the range will be 0
    #     set_tile_cols: [1,32]  # same as for the rows
    #   string_tag: 
    #     type: Constant
    #     constant_value: 1.0
