#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  t: 60
  in0_mblock_m: 1
  in0_mblock_n: 13
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 2
  in1_mblock_n: 13
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 2
  in2_mblock_n: 13
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 2
  in3_mblock_n: 13
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 4
  mblock_n: 13
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x18294fe0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x1dad42e0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x1f0c6100]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x2dc4bb20]]'
  in_attributes: '{input0: [2, 11, 11], input1: [14, 12, 12], input2: [13, 13, 13], input3: [10, 16, 16]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 1
  grid_loc_x: 5
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[4, 0x3cf552e0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 4
  out_mblock_n: 39
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 1
  t: 18
  in0_mblock_m: 6
  in0_mblock_n: 4
  in0_ublock_rt: 4
  in0_ublock_ct: 1
  in1_mblock_m: 3
  in1_mblock_n: 4
  in1_ublock_rt: 4
  in1_ublock_ct: 1
  in2_mblock_m: 1
  in2_mblock_n: 4
  in2_ublock_rt: 4
  in2_ublock_ct: 1
  in3_mblock_m: 1
  in3_mblock_n: 4
  in3_ublock_rt: 4
  in3_ublock_ct: 1
  mblock_m: 3
  mblock_n: 4
  ublock_rt: 4
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[5, 0x30dcb0c0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[5, 0x314d3540]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[5, 0x31bbcb80]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[5, 0x39f0ea40]]'
  in_attributes: '{input0: [13, 8, 11], input1: [6, 1, 6], input2: [1, 2, 3], input3: [2, 1, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 5
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[5, 0x3eacde80]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 3
  out_mblock_n: 4
  out_ublock_rt: 4
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 4
  grid_size_y: 1
  t: 8
  in0_mblock_m: 1
  in0_mblock_n: 14
  in0_ublock_rt: 1
  in0_ublock_ct: 4
  in1_mblock_m: 1
  in1_mblock_n: 14
  in1_ublock_rt: 1
  in1_ublock_ct: 4
  in2_mblock_m: 1
  in2_mblock_n: 14
  in2_ublock_rt: 1
  in2_ublock_ct: 4
  in3_mblock_m: 1
  in3_mblock_n: 14
  in3_ublock_rt: 1
  in3_ublock_ct: 4
  mblock_m: 2
  mblock_n: 14
  ublock_rt: 1
  ublock_ct: 4
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[2, 0x230e7d80], [5, 0x232d1da0], [4, 0x234bbdc0], [2, 0x236a5de0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[2, 0x241da620], [5, 0x243c4640], [4, 0x245ae660], [2, 0x24798680]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[2, 0x278e3c40], [5, 0x27acdc60], [4, 0x27cb7c80], [2, 0x27ea1ca0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[2, 0x30fe6ba0], [5, 0x311d0bc0], [4, 0x313babe0], [2, 0x315a4c00]]'
  in_attributes: '{input0: [6, 8, 8], input1: [6, 8, 8], input2: [9, 5, 5], input3: [7, 7, 7]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 3
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[2, 0x34368180]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 224
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 1
  t: 48
  in0_mblock_m: 8
  in0_mblock_n: 4
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 3
  in1_mblock_n: 4
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 1
  in2_mblock_n: 4
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 2
  in3_mblock_n: 4
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 9
  mblock_n: 4
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[2, 0x12089680]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[2, 0x1604bd20]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[2, 0x1cb978c0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[2, 0x27195140]]'
  in_attributes: '{input0: [16, 16, 16], input1: [1, 11, 11], input2: [1, 3, 3], input3: [2, 6, 6]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x3954b40]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 9
  out_mblock_n: 12
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 4
  grid_size_y: 1
  t: 30
  in0_mblock_m: 4
  in0_mblock_n: 5
  in0_ublock_rt: 4
  in0_ublock_ct: 1
  in1_mblock_m: 5
  in1_mblock_n: 5
  in1_ublock_rt: 4
  in1_ublock_ct: 1
  in2_mblock_m: 1
  in2_mblock_n: 5
  in2_ublock_rt: 4
  in2_ublock_ct: 1
  in3_mblock_m: 3
  in3_mblock_n: 5
  in3_ublock_rt: 4
  in3_ublock_ct: 1
  mblock_m: 7
  mblock_n: 5
  ublock_rt: 4
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x2bcfe360], [3, 0x2c21eb80], [2, 0x2c73f3a0], [5, 0x2cc5fbc0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x2d5f25a0], [3, 0x2dc5afc0], [2, 0x2e2c39e0], [5, 0x2e92c400]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x2f75b200], [3, 0x2f8a3420], [2, 0x2f9eb640], [5, 0x2fb33860]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x307bd940], [3, 0x30b95f60], [2, 0x30f6e580], [5, 0x31346ba0]]'
  in_attributes: '{input0: [4, 15, 16], input1: [16, 9, 9], input2: [1, 3, 4], input3: [6, 8, 9]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 1
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x1bcda40]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 28
  out_mblock_n: 20
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=5
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 4
  grid_size_y: 1
  t: 8
  in0_mblock_m: 2
  in0_mblock_n: 14
  in0_ublock_rt: 1
  in0_ublock_ct: 4
  in1_mblock_m: 2
  in1_mblock_n: 14
  in1_ublock_rt: 1
  in1_ublock_ct: 4
  in2_mblock_m: 1
  in2_mblock_n: 14
  in2_ublock_rt: 1
  in2_ublock_ct: 4
  in3_mblock_m: 1
  in3_mblock_n: 14
  in3_ublock_rt: 1
  in3_ublock_ct: 4
  mblock_m: 2
  mblock_n: 14
  ublock_rt: 1
  ublock_ct: 4
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x15cbee60], [5, 0x15ea8e80], [2, 0x16092ea0], [0, 0x1627cec0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x187da380], [5, 0x189c43a0], [2, 0x18bae3c0], [0, 0x18d983e0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[0, 0x28298f00], [5, 0x2838df20], [2, 0x28482f40], [0, 0x28577f60]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[0, 0x34424120], [5, 0x34519140], [2, 0x3460e160], [0, 0x34703180]]'
  in_attributes: '{input0: [14, 13, 14], input1: [14, 6, 14], input2: [2, 7, 12], input3: [12, 2, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 3
  grid_loc_y: 6
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[0, 0x3b4e69c0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 224
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=6
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 1
  t: 14
  in0_mblock_m: 1
  in0_mblock_n: 10
  in0_ublock_rt: 1
  in0_ublock_ct: 2
  in1_mblock_m: 3
  in1_mblock_n: 10
  in1_ublock_rt: 1
  in1_ublock_ct: 2
  in2_mblock_m: 3
  in2_mblock_n: 10
  in2_ublock_rt: 1
  in2_ublock_ct: 2
  in3_mblock_m: 1
  in3_mblock_n: 10
  in3_ublock_rt: 1
  in3_ublock_ct: 2
  mblock_m: 4
  mblock_n: 10
  ublock_rt: 1
  ublock_ct: 2
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[5, 0x3b7b2060]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[5, 0x3ba23cc0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[5, 0x3c3eb460]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[5, 0x3eb73da0]]'
  in_attributes: '{input0: [6, 2, 4], input1: [15, 15, 15], input2: [14, 16, 16], input3: [3, 7, 7]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 2
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x1c06f60]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 4
  out_mblock_n: 20
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=7
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 1
  t: 54
  in0_mblock_m: 3
  in0_mblock_n: 8
  in0_ublock_rt: 4
  in0_ublock_ct: 1
  in1_mblock_m: 2
  in1_mblock_n: 8
  in1_ublock_rt: 4
  in1_ublock_ct: 1
  in2_mblock_m: 3
  in2_mblock_n: 8
  in2_ublock_rt: 4
  in2_ublock_ct: 1
  in3_mblock_m: 4
  in3_mblock_n: 8
  in3_ublock_rt: 4
  in3_ublock_ct: 1
  mblock_m: 5
  mblock_n: 8
  ublock_rt: 4
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x1613da60]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x1d31e2a0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x21f6d7c0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x25e84ae0]]'
  in_attributes: '{input0: [9, 7, 15], input1: [2, 11, 14], input2: [12, 8, 12], input3: [16, 14, 16]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 7
  grid_loc_y: 7
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x22385c0]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 20
  out_mblock_n: 8
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=8
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 2
  grid_size_y: 1
  t: 54
  in0_mblock_m: 2
  in0_mblock_n: 3
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 9
  in1_mblock_n: 3
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 5
  in2_mblock_n: 3
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 1
  in3_mblock_n: 3
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 8
  mblock_n: 3
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x133d60a0], [2, 0x13c244c0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x16618c00], [2, 0x18b78e20]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x2f0a65c0], [2, 0x30569fe0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x39b2dae0], [2, 0x39f54d00]]'
  in_attributes: '{input0: [1, 5, 5], input1: [16, 5, 11], input2: [3, 12, 12], input3: [1, 2, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x15aa9c0]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 8
  out_mblock_n: 18
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=9
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 2
  grid_size_y: 1
  t: 46
  in0_mblock_m: 7
  in0_mblock_n: 2
  in0_ublock_rt: 1
  in0_ublock_ct: 1
  in1_mblock_m: 12
  in1_mblock_n: 2
  in1_ublock_rt: 1
  in1_ublock_ct: 1
  in2_mblock_m: 5
  in2_mblock_n: 2
  in2_ublock_rt: 1
  in2_ublock_ct: 1
  in3_mblock_m: 5
  in3_mblock_n: 2
  in3_ublock_rt: 1
  in3_ublock_ct: 1
  mblock_m: 16
  mblock_n: 2
  ublock_rt: 1
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x1f838be0], [3, 0x1f998f00]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x20b754e0], [3, 0x20dd1100]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[0, 0x25d6cfa0], [3, 0x25e688c0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[0, 0x2bde1aa0], [3, 0x2bedd3c0]]'
  in_attributes: '{input0: [6, 8, 8], input1: [11, 13, 13], input2: [2, 7, 8], input3: [5, 4, 5]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 5
  grid_loc_y: 6
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[0, 0x3d7719c0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 16
  out_mblock_n: 4
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
