#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  t: 60
  in0_mblock_m: 13
  in0_mblock_n: 5
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 13
  in1_mblock_n: 13
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 13
  in2_mblock_n: 3
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 13
  in3_mblock_n: 4
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 13
  mblock_n: 5
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x19f5ecc0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x1d30a1e0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x2596aa20]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x27784e40]]'
  in_attributes: '{input0: [4, 1, 1], input1: [6, 1, 7], input2: [1, 1, 2], input3: [2, 2, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[4, 0x32f8a680]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 13
  out_mblock_n: 15
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 4
  t: 2
  in0_mblock_m: 5
  in0_mblock_n: 6
  in0_ublock_rt: 4
  in0_ublock_ct: 1
  in1_mblock_m: 5
  in1_mblock_n: 6
  in1_ublock_rt: 4
  in1_ublock_ct: 1
  in2_mblock_m: 5
  in2_mblock_n: 11
  in2_ublock_rt: 4
  in2_ublock_ct: 1
  in3_mblock_m: 5
  in3_mblock_n: 2
  in3_ublock_rt: 4
  in3_ublock_ct: 1
  mblock_m: 5
  mblock_n: 13
  ublock_rt: 4
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[5, 0x3af7d740], [4, 0x3b000b60], [0, 0x3b083f80], [5, 0x3b1073a0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[5, 0x3c4046c0], [4, 0x3c487ae0], [0, 0x3c50af00], [5, 0x3c58e320]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[5, 0x3cf57120], [4, 0x3d047b40], [0, 0x3d138560], [5, 0x3d228f80]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[5, 0x3e0c2360], [4, 0x3e0edf80], [0, 0x3e119ba0], [5, 0x3e1457c0]]'
  in_attributes: '{input0: [3, 2, 3], input1: [2, 1, 4], input2: [1, 9, 10], input3: [1, 1, 1]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 1
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[5, 0x3edcd220]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 80
  out_mblock_n: 13
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  t: 10
  in0_mblock_m: 14
  in0_mblock_n: 11
  in0_ublock_rt: 1
  in0_ublock_ct: 4
  in1_mblock_m: 14
  in1_mblock_n: 3
  in1_ublock_rt: 1
  in1_ublock_ct: 4
  in2_mblock_m: 14
  in2_mblock_n: 9
  in2_ublock_rt: 1
  in2_ublock_ct: 4
  in3_mblock_m: 14
  in3_mblock_n: 16
  in3_ublock_rt: 1
  in3_ublock_ct: 4
  mblock_m: 14
  mblock_n: 15
  ublock_rt: 1
  ublock_ct: 4
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[2, 0x27c7eaa0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[2, 0x298afda0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[2, 0x2a96b840]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[2, 0x2dbdd2a0]]'
  in_attributes: '{input0: [2, 3, 9], input1: [1, 1, 2], input2: [1, 3, 8], input3: [7, 8, 9]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 4
  grid_loc_y: 7
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[2, 0x36c27f40]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 14
  out_mblock_n: 60
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 5
  t: 10
  in0_mblock_m: 4
  in0_mblock_n: 11
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 4
  in1_mblock_n: 6
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 4
  in2_mblock_n: 11
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 4
  in3_mblock_n: 4
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 4
  mblock_n: 8
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[2, 0x21838fc0], [3, 0x223807e0], [5, 0x22ec8000], [3, 0x23a0f820], [4, 0x24557040]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[2, 0x25238ac0], [3, 0x2585fae0], [5, 0x25e86b00], [3, 0x264adb20], [4, 0x26ad4b40]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[2, 0x27e84300], [3, 0x289cbb20], [5, 0x29513340], [3, 0x2a05ab60], [4, 0x2aba2380]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[2, 0x2f058880], [3, 0x2f4728a0], [5, 0x2f88c8c0], [3, 0x2fca68e0], [4, 0x300c0900]]'
  in_attributes: '{input0: [1, 4, 10], input1: [3, 1, 3], input2: [5, 2, 6], input3: [1, 1, 3]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 7
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x35b7040]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 20
  out_mblock_n: 24
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 7
  t: 1
  in0_mblock_m: 10
  in0_mblock_n: 5
  in0_ublock_rt: 2
  in0_ublock_ct: 1
  in1_mblock_m: 10
  in1_mblock_n: 16
  in1_ublock_rt: 2
  in1_ublock_ct: 1
  in2_mblock_m: 10
  in2_mblock_n: 12
  in2_ublock_rt: 2
  in2_ublock_ct: 1
  in3_mblock_m: 10
  in3_mblock_n: 3
  in3_ublock_rt: 2
  in3_ublock_ct: 1
  mblock_m: 10
  mblock_n: 15
  ublock_rt: 2
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x2bbe1ce0], [3, 0x2bc18800], [2, 0x2bc4f320], [5, 0x2bc85e40], [3, 0x2bcbc960], [2, 0x2bcf3480], [4, 0x2bd29fa0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x2dd56660], [3, 0x2de05680], [2, 0x2deb46a0], [5, 0x2df636c0], [3, 0x2e0126e0], [2, 0x2e0c1700], [4, 0x2e170720]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x39568440], [3, 0x395eb860], [2, 0x3966ec80], [5, 0x396f20a0], [3, 0x397754c0], [2, 0x397f88e0], [4, 0x3987bd00]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x39ca0d80], [3, 0x39cc1aa0], [2, 0x39ce27c0], [5, 0x39d034e0], [3, 0x39d24200], [2, 0x39d44f20], [4, 0x39d65c40]]'
  in_attributes: '{input0: [3, 2, 2], input1: [8, 2, 8], input2: [1, 10, 11], input3: [1, 1, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 4
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x9d0fac0]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 140
  out_mblock_n: 15
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=5
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 2
  t: 56
  in0_mblock_m: 14
  in0_mblock_n: 2
  in0_ublock_rt: 1
  in0_ublock_ct: 4
  in1_mblock_m: 14
  in1_mblock_n: 15
  in1_ublock_rt: 1
  in1_ublock_ct: 4
  in2_mblock_m: 14
  in2_mblock_n: 8
  in2_ublock_rt: 1
  in2_ublock_ct: 4
  in3_mblock_m: 14
  in3_mblock_n: 7
  in3_ublock_rt: 1
  in3_ublock_ct: 4
  mblock_m: 14
  mblock_n: 11
  ublock_rt: 1
  ublock_ct: 4
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x1305a200], [5, 0x13dc0220]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x167b3b60], [5, 0x1cc30b80]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[0, 0x25978cc0], [5, 0x28f10ce0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[0, 0x2cc18a40], [5, 0x2fafda60]]'
  in_attributes: '{input0: [1, 1, 1], input1: [4, 8, 11], input2: [4, 1, 4], input3: [5, 1, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 6
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[0, 0x350b9680]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 28
  out_mblock_n: 44
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=6
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 2
  t: 18
  in0_mblock_m: 16
  in0_mblock_n: 10
  in0_ublock_rt: 1
  in0_ublock_ct: 2
  in1_mblock_m: 16
  in1_mblock_n: 7
  in1_ublock_rt: 1
  in1_ublock_ct: 2
  in2_mblock_m: 16
  in2_mblock_n: 4
  in2_ublock_rt: 1
  in2_ublock_ct: 2
  in3_mblock_m: 16
  in3_mblock_n: 15
  in3_ublock_rt: 1
  in3_ublock_ct: 2
  mblock_m: 16
  mblock_n: 12
  ublock_rt: 1
  ublock_ct: 2
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[5, 0x14cddde0], [4, 0x16579e00]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[5, 0x18a2c6a0], [4, 0x19b666c0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[5, 0x24009cc0], [4, 0x249e1ce0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[5, 0x3563c9c0], [4, 0x37b269e0]]'
  in_attributes: '{input0: [5, 3, 5], input1: [2, 5, 5], input2: [1, 2, 3], input3: [2, 2, 13]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x285a1e0]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 32
  out_mblock_n: 24
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=7
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 3
  t: 4
  in0_mblock_m: 8
  in0_mblock_n: 12
  in0_ublock_rt: 4
  in0_ublock_ct: 1
  in1_mblock_m: 8
  in1_mblock_n: 7
  in1_ublock_rt: 4
  in1_ublock_ct: 1
  in2_mblock_m: 8
  in2_mblock_n: 10
  in2_ublock_rt: 4
  in2_ublock_ct: 1
  in3_mblock_m: 8
  in3_mblock_n: 5
  in3_ublock_rt: 4
  in3_ublock_ct: 1
  mblock_m: 8
  mblock_n: 14
  ublock_rt: 4
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x1d0423e0], [5, 0x1d6d2400], [1, 0x1dd62420]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x210031e0], [5, 0x213d7200], [1, 0x217ab220]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x22e3afc0], [5, 0x233b2fe0], [1, 0x2392b000]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x24e99f60], [5, 0x25155f80], [1, 0x25411fa0]]'
  in_attributes: '{input0: [9, 2, 3], input1: [3, 3, 4], input2: [2, 7, 8], input3: [3, 2, 2]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x8f98c60]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 96
  out_mblock_n: 14
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=8
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 6
  t: 20
  in0_mblock_m: 3
  in0_mblock_n: 4
  in0_ublock_rt: 1
  in0_ublock_ct: 3
  in1_mblock_m: 3
  in1_mblock_n: 15
  in1_ublock_rt: 1
  in1_ublock_ct: 3
  in2_mblock_m: 3
  in2_mblock_n: 9
  in2_ublock_rt: 1
  in2_ublock_ct: 3
  in3_mblock_m: 3
  in3_mblock_n: 9
  in3_ublock_rt: 1
  in3_ublock_ct: 3
  mblock_m: 3
  mblock_n: 7
  ublock_rt: 1
  ublock_ct: 3
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[4, 0x13abaf40], [2, 0x140e1f60], [1, 0x14708f80], [1, 0x14d2ffa0], [4, 0x15356fc0], [0, 0x1597dfe0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[4, 0x16fd3220], [2, 0x186e5640], [1, 0x19df7a60], [1, 0x1b509e80], [4, 0x1cc1c2a0], [0, 0x1e32e6c0]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[4, 0x20028720], [2, 0x20e00340], [1, 0x21bd7f60], [1, 0x229afb80], [4, 0x237877a0], [0, 0x2455f3c0]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[4, 0x253ddc60], [2, 0x261b5880], [1, 0x26f8d4a0], [1, 0x27d650c0], [4, 0x28b3cce0], [0, 0x29914900]]'
  in_attributes: '{input0: [1, 1, 3], input1: [9, 1, 6], input2: [3, 4, 6], input3: [8, 1, 1]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int8'
  target_device: 0
  input_count: 2
  grid_loc_x: 1
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'host'
  out_dram_buffers: '[0x9dcd620]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 18
  out_mblock_n: 21
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=9
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  t: 22
  in0_mblock_m: 2
  in0_mblock_n: 8
  in0_ublock_rt: 1
  in0_ublock_ct: 1
  in1_mblock_m: 2
  in1_mblock_n: 12
  in1_ublock_rt: 1
  in1_ublock_ct: 1
  in2_mblock_m: 2
  in2_mblock_n: 5
  in2_ublock_rt: 1
  in2_ublock_ct: 1
  in3_mblock_m: 2
  in3_mblock_n: 6
  in3_ublock_rt: 1
  in3_ublock_ct: 1
  mblock_m: 2
  mblock_n: 9
  ublock_rt: 1
  ublock_ct: 1
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x31ffc0c0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x34704440]]'
  in2_data_format: 'Int8'
  in2_dram_buffers: '[[0, 0x36f1a580]]'
  in3_data_format: 'Int8'
  in3_dram_buffers: '[[0, 0x3e6f0880]]'
  in_attributes: '{input0: [5, 1, 3], input1: [5, 3, 7], input2: [1, 4, 4], input3: [5, 1, 1]}'
  dest_accumulate_data_format: 'Int32'
  out_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 6
  grid_loc_y: 6
  math_fidelity: HiFi4
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_buffer_loc: 'dram'
  out_dram_buffers: '[[0, 0x3edd8820]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 9
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
