#ntb_random_seed=0
#Test id=0
- device: GRAYSKULL
  entries: 2
  grid_size_x: 6
  grid_size_y: 2
  in1_grid_size_x: 2
  in1_grid_size_y: 6
  input_q_t: 2
  output_q_t: 2
  mblock_m: 3
  mblock_n: 2
  mblock_k: 1
  ublock_rt: 5
  ublock_ct: 1
  ublock_kt: 1
  in1_mblock_n: 3
  in1_mblock_k: 2
  in1_ublock_ct: 1
  in1_ublock_kt: 1
  m_k: 6
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: none
  out_data_format: 'Bfp8'
  intermed_data_format: 'Bfp8'
  in0_data_format: 'Bfp8'
  in0_dram_buffers: '[[6, 0x3e45dcc0], [2, 0x3e46e360], [6, 0x3e47ea00], [0, 0x3e48f0a0], [4, 0x3e49f740], [0, 0x3e4afde0], [0, 0x3e4c0480], [7, 0x3e4d0b20], [4, 0x3e4e11c0], [4, 0x3e4f1860], [1, 0x3e501f00], [3, 0x3e5125a0]]'
  in1_data_format: 'Bfp2'
  in1_dram_buffers: '[[6, 0x3e69b2e0], [2, 0x3e69d400], [6, 0x3e69f520], [0, 0x3e6a1640], [4, 0x3e6a3760], [0, 0x3e6a5880], [0, 0x3e6a79a0], [7, 0x3e6a9ac0], [4, 0x3e6abbe0], [4, 0x3e6add00], [1, 0x3e6afe20], [3, 0x3e6b1f40]]'
  in2_data_format: 'Float16'
  in2_dram_buffers: '[[6, 0x3e6cd660], [2, 0x3e70a580], [6, 0x3e7474a0], [0, 0x3e7843c0], [4, 0x3e7c12e0], [0, 0x3e7fe200]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'math'
  relu_en: ' true'
  relu_mode: 'max'
  relu_threshold: '0.700000'
  z: 0
  min_buffer_input: 0
  target_device: 0
  input_count: 1
  grid_loc_x: 2
  grid_loc_y: 6
  math_fidelity: HiFi2
  untilize_output: 'false'
  transpose_in1: [transpose]
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[6, 0x3e9ac800], [2, 0x3e9cd520], [6, 0x3e9ee240], [0, 0x3ea0ef60], [4, 0x3ea2fc80], [0, 0x3ea509a0], [0, 0x3ea716c0], [7, 0x3ea923e0], [4, 0x3eab3100], [4, 0x3ead3e20], [1, 0x3eaf4b40], [3, 0x3eb15860]]'
  out_grid_size_x: 6
  out_grid_size_y: 2
  out_mblock_m: 3
  out_mblock_n: 2
  out_ublock_rt: 5
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.4
  comparison_config_check_pcc: 0.8
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
#Test id=1
- device: GRAYSKULL
  entries: 4
  grid_size_x: 1
  grid_size_y: 3
  in1_grid_size_x: 1
  in1_grid_size_y: 3
  input_q_t: 2
  output_q_t: 2
  mblock_m: 2
  mblock_n: 1
  mblock_k: 3
  ublock_rt: 1
  ublock_ct: 5
  ublock_kt: 1
  in1_mblock_n: 1
  in1_mblock_k: 1
  in1_ublock_ct: 5
  in1_ublock_kt: 1
  m_k: 3
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: none
  out_data_format: 'Float16_b'
  intermed_data_format: 'Float16_b'
  in0_data_format: 'Bfp8_b'
  in0_dram_buffers: '[[2, 0x29af64c0], [5, 0x29b036e0], [0, 0x29b10900]]'
  in1_data_format: 'Bfp8_b'
  in1_dram_buffers: '[[2, 0x2a53c820], [5, 0x2a547740], [0, 0x2a552660]]'
  in2_data_format: 'Float16_b'
  in2_dram_buffers: '[[2, 0x2ff1d980]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'gelu'
  sfpu_execution_thread: 'math'
  relu_en: 'false'
  relu_mode: 'min'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 1
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 3
  math_fidelity: LoFi
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x38917200], [5, 0x3893fc20], [0, 0x38968640]]'
  out_grid_size_x: 1
  out_grid_size_y: 3
  out_mblock_m: 2
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 5
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.7
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
#Test id=2
- device: GRAYSKULL
  entries: 2
  grid_size_x: 2
  grid_size_y: 4
  in1_grid_size_x: 4
  in1_grid_size_y: 2
  input_q_t: 2
  output_q_t: 2
  mblock_m: 1
  mblock_n: 2
  mblock_k: 2
  ublock_rt: 1
  ublock_ct: 2
  ublock_kt: 1
  in1_mblock_n: 1
  in1_mblock_k: 2
  in1_ublock_ct: 1
  in1_ublock_kt: 2
  m_k: 4
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: none
  out_data_format: 'Float16'
  intermed_data_format: 'Float16'
  in0_data_format: 'Float16'
  in0_dram_buffers: '[[7, 0x12f42b60], [7, 0x12f46c80], [0, 0x12f4ada0], [3, 0x12f4eec0], [1, 0x12f52fe0], [4, 0x12f57100], [2, 0x12f5b220], [1, 0x12f5f340]]'
  in1_data_format: 'Bfp8'
  in1_dram_buffers: '[[7, 0x18cee5e0], [7, 0x18cf2c00], [0, 0x18cf7220], [3, 0x18cfb840], [1, 0x18cffe60], [4, 0x18d04480], [2, 0x18d08aa0], [1, 0x18d0d0c0]]'
  in2_data_format: 'Float16'
  in2_dram_buffers: '[[7, 0x1a43b4c0], [7, 0x1a4436e0]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'math'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 0
  target_device: 0
  input_count: 1
  grid_loc_x: 3
  grid_loc_y: 3
  math_fidelity: LoFi
  untilize_output: 'false'
  transpose_in1: [transpose]
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[7, 0x2a5ff040], [7, 0x2a607260], [0, 0x2a60f480], [3, 0x2a6176a0], [1, 0x2a61f8c0], [4, 0x2a627ae0], [2, 0x2a62fd00], [1, 0x2a637f20]]'
  out_grid_size_x: 2
  out_grid_size_y: 4
  out_mblock_m: 1
  out_mblock_n: 2
  out_ublock_rt: 1
  out_ublock_ct: 2
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.7
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
