#Test id=0
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [5, 8], t: 1, mblock: [8, 8], ublock: [3, 1], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3775ef80], [0, 0x37821fc0], [0, 0x378e5000], [0, 0x379a8040], [0, 0x37a6b080], [0, 0x37b2e0c0], [0, 0x37bf1100], [0, 0x37cb4140], [0, 0x37d77180], [0, 0x37e3a1c0], [0, 0x37efd200], [0, 0x37fc0240], [0, 0x38083280], [0, 0x381462c0], [0, 0x38209300], [0, 0x382cc340], [0, 0x3838f380], [0, 0x384523c0], [0, 0x38515400], [0, 0x385d8440], [0, 0x3869b480], [0, 0x3875e4c0], [0, 0x38821500], [0, 0x388e4540], [0, 0x389a7580], [0, 0x38a6a5c0], [0, 0x38b2d600], [0, 0x38bf0640], [0, 0x38cb3680], [0, 0x38d766c0], [0, 0x38e39700], [0, 0x38efc740], [0, 0x38fbf780], [0, 0x390827c0], [0, 0x39145800], [0, 0x39208840], [0, 0x392cb880], [0, 0x3938e8c0], [0, 0x39451900], [0, 0x39514940]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [5, 8], t: 1, mblock: [3, 4], ublock: [2, 2], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3a7bc6c0], [0, 0x3a7ed300], [0, 0x3a81df40], [0, 0x3a84eb80], [0, 0x3a87f7c0], [0, 0x3a8b0400], [0, 0x3a8e1040], [0, 0x3a911c80], [0, 0x3a9428c0], [0, 0x3a973500], [0, 0x3a9a4140], [0, 0x3a9d4d80], [0, 0x3aa059c0], [0, 0x3aa36600], [0, 0x3aa67240], [0, 0x3aa97e80], [0, 0x3aac8ac0], [0, 0x3aaf9700], [0, 0x3ab2a340], [0, 0x3ab5af80], [0, 0x3ab8bbc0], [0, 0x3abbc800], [0, 0x3abed440], [0, 0x3ac1e080], [0, 0x3ac4ecc0], [0, 0x3ac7f900], [0, 0x3acb0540], [0, 0x3ace1180], [0, 0x3ad11dc0], [0, 0x3ad42a00], [0, 0x3ad73640], [0, 0x3ada4280], [0, 0x3add4ec0], [0, 0x3ae05b00], [0, 0x3ae36740], [0, 0x3ae67380], [0, 0x3ae97fc0], [0, 0x3aec8c00], [0, 0x3aef9840], [0, 0x3af2a480]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [5, 8], t: 1, mblock: [8, 8], ublock: [3, 1], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xd6fb340], [0, 0xd731380], [0, 0xd7673c0], [0, 0xd79d400], [0, 0xd7d3440], [0, 0xd809480], [0, 0xd83f4c0], [0, 0xd875500], [0, 0xd8ab540], [0, 0xd8e1580], [0, 0xd9175c0], [0, 0xd94d600], [0, 0xd983640], [0, 0xd9b9680], [0, 0xd9ef6c0], [0, 0xda25700], [0, 0xda5b740], [0, 0xda91780], [0, 0xdac77c0], [0, 0xdafd800], [0, 0xdb33840], [0, 0xdb69880], [0, 0xdb9f8c0], [0, 0xdbd5900], [0, 0xdc0b940], [0, 0xdc41980], [0, 0xdc779c0], [0, 0xdcada00], [0, 0xdce3a40], [0, 0xdd19a80], [0, 0xdd4fac0], [0, 0xdd85b00], [0, 0xddbbb40], [0, 0xddf1b80], [0, 0xde27bc0], [0, 0xde5dc00], [0, 0xde93c40], [0, 0xdec9c80], [0, 0xdeffcc0], [0, 0xdf35d00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: add, grid_size: [5, 8], t: 1, mblock: [8, 8], ublock: [3, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int32, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], input_1_tms: [broadcast: {r: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.90, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [2, 1], t: 1, mblock: [1, 6], ublock: [9, 6], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x23fe73c0], [0, 0x24153c00]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [2, 1], t: 4, mblock: [1, 6], ublock: [3, 6], df: Int32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2aa7efc0], [0, 0x2b15a000]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [2, 1], t: 4, mblock: [9, 12], ublock: [1, 3], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xedf6c80], [0, 0xf3a8cc0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: add, grid_size: [2, 1], t: 4, mblock: [9, 12], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {stoch_rnd_mode: fpu, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {z: 4}, ], input_1_tms: [broadcast: {r: 3}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.90, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 8, mblock: [1, 1], ublock: [1, 6], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x207755c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 1], ublock: [1, 6], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x2a8f0cc0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 8, mblock: [5, 2], ublock: [1, 3], df: Int32, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xa3e1000]], }'
  queue_settings_out0: ''
  op0: 'op: {type: add, grid_size: [1, 1], t: 8, mblock: [5, 2], ublock: [1, 3], out_df: Int32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {kernel_broadcast : {input_1 : 18}, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 5}, ], input_1_tms: [broadcast: {r: 5}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.90, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [4, 1], t: 1, mblock: [11, 3], ublock: [1, 2], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x295efc00], [0, 0x29632cc0], [0, 0x29675d80], [0, 0x296b8e40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [4, 1], t: 1, mblock: [11, 6], ublock: [2, 1], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x2b904000], [0, 0x2b929240], [0, 0x2b94e480], [0, 0x2b9736c0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [4, 1], t: 1, mblock: [11, 6], ublock: [2, 1], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xc379600], [0, 0xc39e840], [0, 0xc3c3a80], [0, 0xc3e8cc0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: add, grid_size: [4, 1], t: 1, mblock: [11, 6], ublock: [2, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int32, Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, ], input_1_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.90, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [5, 8], t: 1, mblock: [2, 14], ublock: [5, 2], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x29829840], [0, 0x29878480], [0, 0x298c70c0], [0, 0x29915d00], [0, 0x29964940], [0, 0x299b3580], [0, 0x29a021c0], [0, 0x29a50e00], [0, 0x29a9fa40], [0, 0x29aee680], [0, 0x29b3d2c0], [0, 0x29b8bf00], [0, 0x29bdab40], [0, 0x29c29780], [0, 0x29c783c0], [0, 0x29cc7000], [0, 0x29d15c40], [0, 0x29d64880], [0, 0x29db34c0], [0, 0x29e02100], [0, 0x29e50d40], [0, 0x29e9f980], [0, 0x29eee5c0], [0, 0x29f3d200], [0, 0x29f8be40], [0, 0x29fdaa80], [0, 0x2a0296c0], [0, 0x2a078300], [0, 0x2a0c6f40], [0, 0x2a115b80], [0, 0x2a1647c0], [0, 0x2a1b3400], [0, 0x2a202040], [0, 0x2a250c80], [0, 0x2a29f8c0], [0, 0x2a2ee500], [0, 0x2a33d140], [0, 0x2a38bd80], [0, 0x2a3da9c0], [0, 0x2a429600]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [5, 8], t: 1, mblock: [2, 14], ublock: [1, 2], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x38f6d680], [0, 0x38fa64c0], [0, 0x38fdf300], [0, 0x39018140], [0, 0x39050f80], [0, 0x39089dc0], [0, 0x390c2c00], [0, 0x390fba40], [0, 0x39134880], [0, 0x3916d6c0], [0, 0x391a6500], [0, 0x391df340], [0, 0x39218180], [0, 0x39250fc0], [0, 0x39289e00], [0, 0x392c2c40], [0, 0x392fba80], [0, 0x393348c0], [0, 0x3936d700], [0, 0x393a6540], [0, 0x393df380], [0, 0x394181c0], [0, 0x39451000], [0, 0x39489e40], [0, 0x394c2c80], [0, 0x394fbac0], [0, 0x39534900], [0, 0x3956d740], [0, 0x395a6580], [0, 0x395df3c0], [0, 0x39618200], [0, 0x39651040], [0, 0x39689e80], [0, 0x396c2cc0], [0, 0x396fbb00], [0, 0x39734940], [0, 0x3976d780], [0, 0x397a65c0], [0, 0x397df400], [0, 0x39818240]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [5, 8], t: 8, mblock: [5, 14], ublock: [2, 2], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0x8bf2cc0], [0, 0x8e68d00], [0, 0x90ded40], [0, 0x9354d80], [0, 0x95cadc0], [0, 0x9840e00], [0, 0x9ab6e40], [0, 0x9d2ce80], [0, 0x9fa2ec0], [0, 0xa218f00], [0, 0xa48ef40], [0, 0xa704f80], [0, 0xa97afc0], [0, 0xabf1000], [0, 0xae67040], [0, 0xb0dd080], [0, 0xb3530c0], [0, 0xb5c9100], [0, 0xb83f140], [0, 0xbab5180], [0, 0xbd2b1c0], [0, 0xbfa1200], [0, 0xc217240], [0, 0xc48d280], [0, 0xc7032c0], [0, 0xc979300], [0, 0xcbef340], [0, 0xce65380], [0, 0xd0db3c0], [0, 0xd351400], [0, 0xd5c7440], [0, 0xd83d480], [0, 0xdab34c0], [0, 0xdd29500], [0, 0xdf9f540], [0, 0xe215580], [0, 0xe48b5c0], [0, 0xe701600], [0, 0xe977640], [0, 0xebed680]], }'
  queue_settings_out0: ''
  op0: 'op: {type: add, grid_size: [5, 8], t: 8, mblock: [5, 14], ublock: [2, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {z: 8}, ], input_1_tms: [broadcast: {r: 5}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.90, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
