# SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC

# SPDX-License-Identifier: Apache-2.0
MAX_TENSOR_SIZE_IN_TILES = 16 * 16 * 64
MAX_GATHER_SOURCE_BUFFERS = 8
MAX_FORK_DESTINATION_BUFFERS = 8
MAX_MULTICAST_DESTINATION_BUFFERS = 8
MAX_PIPE_SCATTER_DESTINATION_BUFFERS = 8
