./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1.nightly.yaml --output-dir sample-out-fork1-reblock
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2.nightly.yaml --output-dir sample-out-fork2-reblock
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4.nightly.yaml --output-dir sample-out-fork4-reblock

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-transpose.nightly.yaml --output-dir sample-out-fork1-reblock-transpose 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-transpose.nightly.yaml --output-dir sample-out-fork2-reblock-transpose
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-transpose.nightly.yaml --output-dir sample-out-fork4-reblock-transpose

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-hslice.nightly.yaml --output-dir sample-out-fork1-reblock-hslice 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-hslice.nightly.yaml --output-dir sample-out-fork2-reblock-hslice
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-hslice.nightly.yaml --output-dir sample-out-fork4-reblock-hslice

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-vslice.nightly.yaml --output-dir sample-out-fork1-reblock-vslice 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-vslice.nightly.yaml --output-dir sample-out-fork2-reblock-vslice
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-vslice.nightly.yaml --output-dir sample-out-fork4-reblock-vslice

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-hstack.nightly.yaml --output-dir sample-out-fork1-reblock-hstack 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-hstack.nightly.yaml --output-dir sample-out-fork2-reblock-hstack
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-hstack.nightly.yaml --output-dir sample-out-fork4-reblock-hstack

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-vstack.nightly.yaml --output-dir sample-out-fork1-reblock-vstack 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-vstack.nightly.yaml --output-dir sample-out-fork2-reblock-vstack
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-vstack.nightly.yaml --output-dir sample-out-fork4-reblock-vstack

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork1_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork1-bcast.nightly.yaml --output-dir sample-out-fork1-reblock-bcast 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-bcast.nightly.yaml --output-dir sample-out-fork2-reblock-bcast
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-bcast.nightly.yaml --output-dir sample-out-fork4-reblock-bcast

./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork2_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork2-rand.nightly.yaml --output-dir sample-out-fork2-reblock-rand 
./verif/template_netlist/generate_netlists.py --template-yaml verif/template_netlist/templates/test_datacopy_fork4_datacopy.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/configs/grayskull/tm/test_datacopy_fork_reblock_datacopy_test_configs.fork4-rand.nightly.yaml --output-dir sample-out-fork4-reblock-rand
