source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-hslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-hstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-transpose
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-vslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-vstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock-bcast
source verif/op_tests/scripts/run_tests.sh sample-out-fork1-reblock
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-hslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-hstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-transpose
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-vslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-vstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-hslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-hstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-transpose
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-vslice
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-vstack
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-bcast
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-bcast
source verif/op_tests/scripts/run_tests.sh sample-out-fork2-reblock-rand
source verif/op_tests/scripts/run_tests.sh sample-out-fork4-reblock-rand
