#!/bin/bash

verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/unary/unary_single_configs.yaml --output-dir build/test/unary-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/unary/unary_feeder_drainer_configs.yaml --output-dir build/test/unary-feeder-drainer-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/unary/unary_gradient_acc_single_configs.yaml --output-dir build/test/unary-gradient-acc-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/binary/binary_single_configs.yaml --output-dir build/test/binary-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/binary/binary_feeder_drainer_configs.yaml --output-dir build/test/binary-feeder-drainer-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/binary/binary_gradient_acc_single_configs.yaml --output-dir build/test/binary-gradient-acc-nightly --use-hash 0
unzip verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_single_configs.zip
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_single_configs.yaml --output-dir build/test/matmul-nightly --use-hash 0
rm verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_single_configs.yaml
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_feeder_drainer_configs.yaml --output-dir build/test/matmul-feeder-drainer-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_gradient_acc_single_configs.yaml --output-dir build/test/matmul-gradient-acc-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul/matmul_accumulate_z_single_configs.yaml --output-dir build/test/matmul-accumulate-z-acc-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/depthwise/depthwise_single_configs.yaml --output-dir build/test/depthwise-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/splice/splice_single_configs.yaml --output-dir build/test/splice-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/reduce/reduce_single_configs.yaml --output-dir build/test/reduce-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/blackhole/silicon/matmul_ident/matmul_ident_single_configs.yaml --output-dir build/test/matmul_ident-nightly --use-hash 0