#!/bin/bash

verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/unary/unary_single_int8_configs.yaml --output-dir build/test/unary-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/binary/binary_single_int8_configs.yaml --output-dir build/test/binary-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/binary/binary_sfpu_single_int8_configs.yaml --output-dir build/test/binary-sfpu-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/matmul/matmul_single_int8_configs.yaml --output-dir build/test/matmul-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/matmul/matmul_single_int8_quant_configs.yaml --output-dir build/test/matmul-quant-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/matmul/matmul_acc_z_single_int8_configs.yaml --output-dir build/test/matmul-acc-z-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/matmul_ident/matmul_ident_single_int8_configs.yaml --output-dir build/test/matmul-ident-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/depthwise/depthwise_single_int8_configs.yaml --output-dir build/test/depthwise-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/reduce/reduce_dim_c_single_int8_configs.yaml --output-dir build/test/reduce-dim-c-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/reduce/reduce_dim_r_single_int8_configs.yaml --output-dir build/test/reduce-dim-r-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/reduce/reduce_dim_z_single_int8_configs.yaml --output-dir build/test/reduce-dim-z-int8-nightly --use-hash 0
verif/template_netlist/generate_netlists.py --template-yaml verif/op_tests/netlists/templates/wormhole_b0/netlist_op_test.template.yaml --test-configs-yaml verif/op_tests/constraints/vcs/test_configs/wormhole_b0/splice/splice_single_int8_configs.yaml --output-dir build/test/splice-int8-nightly --use-hash 0