#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 6
  grid_size_y: 1
  in_grid_size_x: 6
  in_grid_size_y: 1
  t: 6
  mblock_m: 16
  mblock_n: 13
  ublock_rt: 1
  ublock_ct: 2
  m_k: ', m_k: 16'
  u_kt: ', u_kt: 1'
  reduced_mblock_m: 1
  reduced_ublock_rt: 1
  reduced_mblock_n: 13
  reduced_ublock_ct: 2
  in_mblock_m: 16
  in_mblock_n: 13
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x19b80b80], [3, 0x1a0d5ba0], [4, 0x1a62abc0], [5, 0x1ab7fbe0], [0, 0x1b0d4c00], [0, 0x1b629c20]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: r
  reduce_z_dim: ''
  grid_loc_x: 2
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x26f98060]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 156
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 6
  # Program vars
  loop_count: 2
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  in_grid_size_x: 1
  in_grid_size_y: 1
  t: 34
  mblock_m: 1
  mblock_n: 5
  ublock_rt: 2
  ublock_ct: 2
  m_k: ', m_k: 1'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 1
  reduced_ublock_rt: 1
  reduced_mblock_n: 5
  reduced_ublock_ct: 2
  in_mblock_m: 1
  in_mblock_n: 5
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[5, 0x247ceca0]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: r
  reduce_z_dim: ''
  grid_loc_x: 2
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x356b4240]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 5
  out_ublock_rt: 1
  out_ublock_ct: 2
  out_t: 34
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 8
  grid_size_y: 1
  in_grid_size_x: 8
  in_grid_size_y: 1
  t: 62
  mblock_m: 8
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 2
  m_k: ', m_k: 8'
  u_kt: ', u_kt: 1'
  reduced_mblock_m: 1
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 2
  in_mblock_m: 8
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x2da259e0], [5, 0x2dc44200], [4, 0x2de62a20], [2, 0x2e081240], [2, 0x2e29fa60], [3, 0x2e4be280], [5, 0x2e6dcaa0], [5, 0x2e8fb2c0]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: r
  reduce_z_dim: ''
  grid_loc_x: 0
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x37867fa0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 16
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 62
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 8
  grid_size_y: 1
  in_grid_size_x: 8
  in_grid_size_y: 1
  t: 8
  mblock_m: 1
  mblock_n: 16
  ublock_rt: 2
  ublock_ct: 2
  m_k: ', m_k: 1'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 1
  reduced_ublock_rt: 1
  reduced_mblock_n: 16
  reduced_ublock_ct: 2
  in_mblock_m: 1
  in_mblock_n: 16
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x128effe0], [3, 0x12b20000], [5, 0x12d50020], [3, 0x12f80040], [4, 0x131b0060], [3, 0x133e0080], [0, 0x136100a0], [5, 0x138400c0]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: r
  reduce_z_dim: ''
  grid_loc_x: 0
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x3455a100]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 256
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 8
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 3
  grid_size_y: 1
  in_grid_size_x: 3
  in_grid_size_y: 1
  t: 26
  mblock_m: 3
  mblock_n: 15
  ublock_rt: 2
  ublock_ct: 1
  m_k: ', m_k: 3'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 1
  reduced_ublock_rt: 1
  reduced_mblock_n: 15
  reduced_ublock_ct: 1
  in_mblock_m: 3
  in_mblock_n: 15
  in_ublock_rt: 2
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x230af720], [3, 0x23aaed40], [2, 0x244ae360]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: r
  reduce_z_dim: ''
  grid_loc_x: 1
  grid_loc_y: 4
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x26d768e0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 45
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 26
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
