#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 6
  in_grid_size_x: 1
  in_grid_size_y: 6
  t: 6
  mblock_m: 16
  mblock_n: 13
  ublock_rt: 1
  ublock_ct: 2
  m_k: ', m_k: 13'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 16
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 1
  in_mblock_m: 16
  in_mblock_n: 13
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x19baa6e0], [3, 0x1a0ff700], [4, 0x1a654720], [5, 0x1aba9740], [0, 0x1b0fe760], [0, 0x1b653780]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: c
  reduce_z_dim: ''
  grid_loc_x: 1
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x26ff20a0]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 96
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 6
  # Program vars
  loop_count: 2
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 1
  in_grid_size_x: 1
  in_grid_size_y: 1
  t: 34
  mblock_m: 6
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 2
  m_k: ', m_k: 1'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 6
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 1
  in_mblock_m: 6
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[5, 0x1e0b7700]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: c
  reduce_z_dim: ''
  grid_loc_x: 2
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x2cb2c380]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 6
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 34
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 8
  in_grid_size_x: 1
  in_grid_size_y: 8
  t: 62
  mblock_m: 2
  mblock_n: 8
  ublock_rt: 1
  ublock_ct: 2
  m_k: ', m_k: 8'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 2
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 1
  in_mblock_m: 2
  in_mblock_n: 8
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x13ddfda0], [5, 0x1421cdc0], [4, 0x14659de0], [2, 0x14a96e00], [2, 0x14ed3e20], [3, 0x15310e40], [5, 0x1574de60], [5, 0x15b8ae80]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: c
  reduce_z_dim: ''
  grid_loc_x: 2
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x30805a40]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 16
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 62
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 8
  in_grid_size_x: 1
  in_grid_size_y: 8
  t: 8
  mblock_m: 4
  mblock_n: 1
  ublock_rt: 2
  ublock_ct: 2
  m_k: ', m_k: 1'
  u_kt: ', u_kt: 2'
  reduced_mblock_m: 4
  reduced_ublock_rt: 2
  reduced_mblock_n: 1
  reduced_ublock_ct: 1
  in_mblock_m: 4
  in_mblock_n: 1
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x3d4ce5a0], [3, 0x3d5e65c0], [5, 0x3d6fe5e0], [3, 0x3d816600], [4, 0x3d92e620], [3, 0x3da46640], [0, 0x3db5e660], [5, 0x3dc76680]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: c
  reduce_z_dim: ''
  grid_loc_x: 1
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x3df37400]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 64
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 8
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 6
  in_grid_size_x: 1
  in_grid_size_y: 6
  t: 38
  mblock_m: 4
  mblock_n: 4
  ublock_rt: 3
  ublock_ct: 1
  m_k: ', m_k: 4'
  u_kt: ', u_kt: 1'
  reduced_mblock_m: 4
  reduced_ublock_rt: 3
  reduced_mblock_n: 1
  reduced_ublock_ct: 1
  in_mblock_m: 4
  in_mblock_n: 4
  in_ublock_rt: 3
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x226ef7e0], [3, 0x22eba800], [2, 0x23685820], [5, 0x23e50840], [3, 0x2461b860], [2, 0x24de6880]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: c
  reduce_z_dim: ''
  grid_loc_x: 1
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output:  'true'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x2737e500]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 72
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 38
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
