#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 6
  grid_size_y: 1
  in_grid_size_x: 6
  in_grid_size_y: 1
  t: 30
  mblock_m: 2
  mblock_n: 16
  ublock_rt: 2
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 2
  reduced_ublock_rt: 2
  reduced_mblock_n: 16
  reduced_ublock_ct: 2
  in_mblock_m: 2
  in_mblock_n: 16
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x1d5d5940], [3, 0x1e63d960], [4, 0x1f6a5980], [5, 0x2070d9a0], [0, 0x217759c0], [0, 0x227dd9e0]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 5'
  grid_loc_x: 2
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x2d264ec0], [3, 0x2d5acee0], [4, 0x2d8f4f00], [5, 0x2dc3cf20], [0, 0x2df84f40], [0, 0x2e2ccf60]]'
  out_grid_size_x: 6
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 16
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_t: 6
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 3
  grid_size_y: 3
  in_grid_size_x: 3
  in_grid_size_y: 3
  t: 26
  mblock_m: 8
  mblock_n: 2
  ublock_rt: 1
  ublock_ct: 4
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 8
  reduced_ublock_rt: 1
  reduced_mblock_n: 2
  reduced_ublock_ct: 4
  in_mblock_m: 8
  in_mblock_n: 2
  in_ublock_rt: 1
  in_ublock_ct: 4
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[5, 0x2c30d120], [4, 0x2c69b140], [0, 0x2ca29160], [5, 0x2cdb7180], [2, 0x2d1451a0], [3, 0x2d4d31c0], [5, 0x2d8611e0], [5, 0x2dbef200], [2, 0x2df7d220]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 13'
  grid_loc_x: 1
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x30c40c40], [4, 0x30c86c60], [0, 0x30cccc80], [5, 0x30d12ca0], [2, 0x30d58cc0], [3, 0x30d9ece0], [5, 0x30de4d00], [5, 0x30e2ad20], [2, 0x30e70d40]]'
  out_grid_size_x: 3
  out_grid_size_y: 3
  out_mblock_m: 8
  out_mblock_n: 2
  out_ublock_rt: 1
  out_ublock_ct: 4
  out_t: 2
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 7
  grid_size_y: 3
  in_grid_size_x: 7
  in_grid_size_y: 3
  t: 64
  mblock_m: 16
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 16
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 2
  in_mblock_m: 16
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x15441500], [5, 0x158a1520], [4, 0x15d01540], [2, 0x16161560], [2, 0x165c1580], [3, 0x16a215a0], [5, 0x16e815c0], [5, 0x172e15e0], [1, 0x17741600], [1, 0x17ba1620], [2, 0x18001640], [5, 0x18461660], [3, 0x188c1680], [2, 0x18d216a0], [0, 0x191816c0], [4, 0x195e16e0], [0, 0x19a41700], [2, 0x19ea1720], [0, 0x1a301740], [4, 0x1a761760], [2, 0x1abc1780]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 1'
  grid_loc_x: 0
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x29da5c60], [5, 0x2a205c80], [4, 0x2a665ca0], [2, 0x2aac5cc0], [2, 0x2af25ce0], [3, 0x2b385d00], [5, 0x2b7e5d20], [5, 0x2bc45d40], [1, 0x2c0a5d60], [1, 0x2c505d80], [2, 0x2c965da0], [5, 0x2cdc5dc0], [3, 0x2d225de0], [2, 0x2d685e00], [0, 0x2dae5e20], [4, 0x2df45e40], [0, 0x2e3a5e60], [2, 0x2e805e80], [0, 0x2ec65ea0], [4, 0x2f0c5ec0], [2, 0x2f525ee0]]'
  out_grid_size_x: 7
  out_grid_size_y: 3
  out_mblock_m: 16
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 2
  out_t: 64
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 5
  grid_size_y: 3
  in_grid_size_x: 5
  in_grid_size_y: 3
  t: 8
  mblock_m: 13
  mblock_n: 9
  ublock_rt: 1
  ublock_ct: 1
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 13
  reduced_ublock_rt: 1
  reduced_mblock_n: 9
  reduced_ublock_ct: 1
  in_mblock_m: 13
  in_mblock_n: 9
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[2, 0x123c3d40], [3, 0x127c3960], [5, 0x12bc3580], [3, 0x12fc31a0], [4, 0x133c2dc0], [3, 0x137c29e0], [0, 0x13bc2600], [5, 0x13fc2220], [0, 0x143c1e40], [4, 0x147c1a60], [5, 0x14bc1680], [0, 0x14fc12a0], [3, 0x153c0ec0], [1, 0x157c0ae0], [3, 0x15bc0700]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 1'
  grid_loc_x: 3
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x328980a0], [3, 0x32c97cc0], [5, 0x330978e0], [3, 0x33497500], [4, 0x33897120], [3, 0x33c96d40], [0, 0x34096960], [5, 0x34496580], [0, 0x348961a0], [4, 0x34c95dc0], [5, 0x350959e0], [0, 0x35495600], [3, 0x35895220], [1, 0x35c94e40], [3, 0x36094a60]]'
  out_grid_size_x: 5
  out_grid_size_y: 3
  out_mblock_m: 13
  out_mblock_n: 9
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 8
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 2
  grid_size_y: 5
  in_grid_size_x: 2
  in_grid_size_y: 5
  t: 62
  mblock_m: 10
  mblock_n: 3
  ublock_rt: 2
  ublock_ct: 1
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 10
  reduced_ublock_rt: 2
  reduced_mblock_n: 3
  reduced_ublock_ct: 1
  in_mblock_m: 10
  in_mblock_n: 3
  in_ublock_rt: 2
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x20dae960], [3, 0x215a0f80], [2, 0x21d935a0], [5, 0x22585bc0], [3, 0x22d781e0], [2, 0x2356a800], [4, 0x23d5ce20], [2, 0x2454f440], [1, 0x24d41a60], [3, 0x25534080]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 2'
  grid_loc_x: 2
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x27865fc0], [3, 0x27c5f2e0], [2, 0x28058600], [5, 0x28451920], [3, 0x2884ac40], [2, 0x28c43f60], [4, 0x2903d280], [2, 0x294365a0], [1, 0x2982f8c0], [3, 0x29c28be0]]'
  out_grid_size_x: 2
  out_grid_size_y: 5
  out_mblock_m: 10
  out_mblock_n: 3
  out_ublock_rt: 2
  out_ublock_ct: 1
  out_t: 31
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=5
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 4
  in_grid_size_x: 1
  in_grid_size_y: 4
  t: 50
  mblock_m: 5
  mblock_n: 4
  ublock_rt: 4
  ublock_ct: 1
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 5
  reduced_ublock_rt: 4
  reduced_mblock_n: 4
  reduced_ublock_ct: 1
  in_mblock_m: 5
  in_mblock_n: 4
  in_ublock_rt: 4
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[0, 0x1e645500], [5, 0x20873520], [2, 0x22aa1540], [0, 0x24ccf560]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 10'
  grid_loc_x: 3
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3a7630a0], [5, 0x3aace0c0], [2, 0x3ae390e0], [0, 0x3b1a4100]]'
  out_grid_size_x: 1
  out_grid_size_y: 4
  out_mblock_m: 5
  out_mblock_n: 4
  out_ublock_rt: 4
  out_ublock_ct: 1
  out_t: 5
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=6
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 4
  grid_size_y: 2
  in_grid_size_x: 4
  in_grid_size_y: 2
  t: 34
  mblock_m: 13
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 13
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 2
  in_mblock_m: 13
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[5, 0x1bee3460], [4, 0x1c2aa280], [5, 0x1c6710a0], [1, 0x1ca37ec0], [1, 0x1cdfece0], [0, 0x1d1c5b00], [5, 0x1d58c920], [1, 0x1d953740]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 17'
  grid_loc_x: 4
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x3216efe0], [4, 0x321a7e00], [5, 0x321e0c20], [1, 0x32219a40], [1, 0x32252860], [0, 0x3228b680], [5, 0x322c44a0], [1, 0x322fd2c0]]'
  out_grid_size_x: 4
  out_grid_size_y: 2
  out_mblock_m: 13
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 2
  out_t: 2
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=7
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 3
  grid_size_y: 3
  in_grid_size_x: 3
  in_grid_size_y: 3
  t: 60
  mblock_m: 6
  mblock_n: 2
  ublock_rt: 2
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 6
  reduced_ublock_rt: 2
  reduced_mblock_n: 2
  reduced_ublock_ct: 2
  in_mblock_m: 6
  in_mblock_n: 2
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x1c783d20], [5, 0x1d3d1d40], [1, 0x1e01fd60], [2, 0x1ec6dd80], [1, 0x1f8bbda0], [4, 0x20509dc0], [2, 0x21157de0], [0, 0x21da5e00], [3, 0x229f3e20]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 4'
  grid_loc_x: 5
  grid_loc_y: 3
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x31f7e420], [5, 0x32291c40], [1, 0x325a5460], [2, 0x328b8c80], [1, 0x32bcc4a0], [4, 0x32edfcc0], [2, 0x331f34e0], [0, 0x33506d00], [3, 0x3381a520]]'
  out_grid_size_x: 3
  out_grid_size_y: 3
  out_mblock_m: 6
  out_mblock_n: 2
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_t: 15
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=8
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 5
  grid_size_y: 7
  in_grid_size_x: 5
  in_grid_size_y: 7
  t: 64
  mblock_m: 9
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 3
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 9
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 3
  in_mblock_m: 9
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 3
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x169f2560], [2, 0x178b6580], [1, 0x1877a5a0], [1, 0x1963e5c0], [4, 0x1a5025e0], [0, 0x1b3c6600], [0, 0x1c28a620], [4, 0x1d14e640], [5, 0x1e012660], [3, 0x1eed6680], [2, 0x1fd9a6a0], [4, 0x20c5e6c0], [0, 0x21b226e0], [0, 0x229e6700], [1, 0x238aa720], [5, 0x2476e740], [2, 0x25632760], [0, 0x264f6780], [5, 0x273ba7a0], [0, 0x2827e7c0], [5, 0x291427e0], [3, 0x2a006800], [5, 0x2aeca820], [2, 0x2bd8e840], [5, 0x2cc52860], [4, 0x2db16880], [5, 0x2e9da8a0], [3, 0x2f89e8c0], [0, 0x307628e0], [0, 0x31626900], [0, 0x324ea920], [3, 0x333ae940], [1, 0x34272960], [5, 0x35136980], [4, 0x35ffa9a0]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 16'
  grid_loc_x: 1
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x3a0ce220], [2, 0x3a1ba640], [1, 0x3a2a6a60], [1, 0x3a392e80], [4, 0x3a47f2a0], [0, 0x3a56b6c0], [0, 0x3a657ae0], [4, 0x3a743f00], [5, 0x3a830320], [3, 0x3a91c740], [2, 0x3aa08b60], [4, 0x3aaf4f80], [0, 0x3abe13a0], [0, 0x3accd7c0], [1, 0x3adb9be0], [5, 0x3aea6000], [2, 0x3af92420], [0, 0x3b07e840], [5, 0x3b16ac60], [0, 0x3b257080], [5, 0x3b3434a0], [3, 0x3b42f8c0], [5, 0x3b51bce0], [2, 0x3b608100], [5, 0x3b6f4520], [4, 0x3b7e0940], [5, 0x3b8ccd60], [3, 0x3b9b9180], [0, 0x3baa55a0], [0, 0x3bb919c0], [0, 0x3bc7dde0], [3, 0x3bd6a200], [1, 0x3be56620], [5, 0x3bf42a40], [4, 0x3c02ee60]]'
  out_grid_size_x: 5
  out_grid_size_y: 7
  out_mblock_m: 9
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 3
  out_t: 4
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=9
- device: WORMHOLE_B0
  entries: 1
  grid_size_x: 8
  grid_size_y: 3
  in_grid_size_x: 8
  in_grid_size_y: 3
  t: 6
  mblock_m: 6
  mblock_n: 16
  ublock_rt: 2
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 6
  reduced_ublock_rt: 2
  reduced_mblock_n: 16
  reduced_ublock_ct: 2
  in_mblock_m: 6
  in_mblock_n: 16
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[0, 0x3a2eaa60], [3, 0x3a560a80], [3, 0x3a7d6aa0], [0, 0x3aa4cac0], [3, 0x3acc2ae0], [5, 0x3af38b00], [0, 0x3b1aeb20], [1, 0x3b424b40], [2, 0x3b69ab60], [1, 0x3b910b80], [0, 0x3bb86ba0], [3, 0x3bdfcbc0], [5, 0x3c072be0], [5, 0x3c2e8c00], [2, 0x3c55ec20], [0, 0x3c7d4c40], [2, 0x3ca4ac60], [3, 0x3ccc0c80], [0, 0x3cf36ca0], [2, 0x3d1accc0], [4, 0x3d422ce0], [1, 0x3d698d00], [4, 0x3d90ed20], [1, 0x3db84d40]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 2'
  grid_loc_x: 0
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3e127500], [3, 0x3e262520], [3, 0x3e39d540], [0, 0x3e4d8560], [3, 0x3e613580], [5, 0x3e74e5a0], [0, 0x3e8895c0], [1, 0x3e9c45e0], [2, 0x3eaff600], [1, 0x3ec3a620], [0, 0x3ed75640], [3, 0x3eeb0660], [5, 0x3efeb680], [5, 0x3f1266a0], [2, 0x3f2616c0], [0, 0x3f39c6e0], [2, 0x3f4d7700], [3, 0x3f612720], [0, 0x3f74d740], [2, 0x3f888760], [4, 0x3f9c3780], [1, 0x3fafe7a0], [4, 0x3fc397c0], [1, 0x3fd747e0]]'
  out_grid_size_x: 8
  out_grid_size_y: 3
  out_mblock_m: 6
  out_mblock_n: 16
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_t: 3
  # Program vars
  loop_count: 1
  queue_wrap_size: 2
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
