#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 6
  grid_size_y: 1
  in_grid_size_x: 6
  in_grid_size_y: 1
  t: 30
  mblock_m: 2
  mblock_n: 16
  ublock_rt: 2
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 2
  reduced_ublock_rt: 2
  reduced_mblock_n: 16
  reduced_ublock_ct: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_mblock_m: 2
  in_mblock_n: 16
  in_ublock_rt: 2
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[3, 0x1d5d5940], [4, 0x1e63d960], [5, 0x1f6a5980], [0, 0x2070d9a0], [0, 0x217759c0], [0, 0x227dd9e0]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 5'
  grid_loc_x: 2
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x2d264ec0], [4, 0x2d5acee0], [5, 0x2d8f4f00], [0, 0x2dc3cf20], [0, 0x2df84f40], [0, 0x2e2ccf60]]'
  out_grid_size_x: 6
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 16
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_t: 6
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 3
  grid_size_y: 3
  in_grid_size_x: 3
  in_grid_size_y: 3
  t: 26
  mblock_m: 8
  mblock_n: 2
  ublock_rt: 1
  ublock_ct: 4
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 8
  reduced_ublock_rt: 1
  reduced_mblock_n: 2
  reduced_ublock_ct: 4
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_mblock_m: 8
  in_mblock_n: 2
  in_ublock_rt: 1
  in_ublock_ct: 4
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[4, 0x2c30d120], [0, 0x2c69b140], [5, 0x2ca29160], [2, 0x2cdb7180], [3, 0x2d1451a0], [5, 0x2d4d31c0], [5, 0x2d8611e0], [2, 0x2dbef200], [5, 0x2df7d220]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 13'
  grid_loc_x: 1
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x30c40c40], [0, 0x30c86c60], [5, 0x30cccc80], [2, 0x30d12ca0], [3, 0x30d58cc0], [5, 0x30d9ece0], [5, 0x30de4d00], [2, 0x30e2ad20], [5, 0x30e70d40]]'
  out_grid_size_x: 3
  out_grid_size_y: 3
  out_mblock_m: 8
  out_mblock_n: 2
  out_ublock_rt: 1
  out_ublock_ct: 4
  out_t: 2
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 7
  grid_size_y: 3
  in_grid_size_x: 7
  in_grid_size_y: 3
  t: 64
  mblock_m: 16
  mblock_n: 1
  ublock_rt: 1
  ublock_ct: 2
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 16
  reduced_ublock_rt: 1
  reduced_mblock_n: 1
  reduced_ublock_ct: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_mblock_m: 16
  in_mblock_n: 1
  in_ublock_rt: 1
  in_ublock_ct: 2
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[5, 0x15441500], [4, 0x158a1520], [2, 0x15d01540], [2, 0x16161560], [3, 0x165c1580], [5, 0x16a215a0], [5, 0x16e815c0], [1, 0x172e15e0], [1, 0x17741600], [2, 0x17ba1620], [5, 0x18001640], [3, 0x18461660], [2, 0x188c1680], [0, 0x18d216a0], [4, 0x191816c0], [0, 0x195e16e0], [2, 0x19a41700], [0, 0x19ea1720], [4, 0x1a301740], [2, 0x1a761760], [3, 0x1abc1780]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 1'
  grid_loc_x: 0
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x29da5c60], [4, 0x2a205c80], [2, 0x2a665ca0], [2, 0x2aac5cc0], [3, 0x2af25ce0], [5, 0x2b385d00], [5, 0x2b7e5d20], [1, 0x2bc45d40], [1, 0x2c0a5d60], [2, 0x2c505d80], [5, 0x2c965da0], [3, 0x2cdc5dc0], [2, 0x2d225de0], [0, 0x2d685e00], [4, 0x2dae5e20], [0, 0x2df45e40], [2, 0x2e3a5e60], [0, 0x2e805e80], [4, 0x2ec65ea0], [2, 0x2f0c5ec0], [3, 0x2f525ee0]]'
  out_grid_size_x: 7
  out_grid_size_y: 3
  out_mblock_m: 16
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 2
  out_t: 64
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 5
  grid_size_y: 3
  in_grid_size_x: 5
  in_grid_size_y: 3
  t: 8
  mblock_m: 13
  mblock_n: 9
  ublock_rt: 1
  ublock_ct: 1
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 13
  reduced_ublock_rt: 1
  reduced_mblock_n: 9
  reduced_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_mblock_m: 13
  in_mblock_n: 9
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[3, 0x123c3d40], [5, 0x127c3960], [3, 0x12bc3580], [4, 0x12fc31a0], [3, 0x133c2dc0], [0, 0x137c29e0], [5, 0x13bc2600], [0, 0x13fc2220], [4, 0x143c1e40], [5, 0x147c1a60], [0, 0x14bc1680], [3, 0x14fc12a0], [1, 0x153c0ec0], [3, 0x157c0ae0], [5, 0x15bc0700]]'
  target_device: 0
  input_count: 2
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 1'
  grid_loc_x: 3
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x328980a0], [5, 0x32c97cc0], [3, 0x330978e0], [4, 0x33497500], [3, 0x33897120], [0, 0x33c96d40], [5, 0x34096960], [0, 0x34496580], [4, 0x348961a0], [5, 0x34c95dc0], [0, 0x350959e0], [3, 0x35495600], [1, 0x35895220], [3, 0x35c94e40], [5, 0x36094a60]]'
  out_grid_size_x: 5
  out_grid_size_y: 3
  out_mblock_m: 13
  out_mblock_n: 9
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_t: 8
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 2
  grid_size_y: 5
  in_grid_size_x: 2
  in_grid_size_y: 5
  t: 62
  mblock_m: 10
  mblock_n: 3
  ublock_rt: 2
  ublock_ct: 1
  m_k: ''
  u_kt: ''
  reduced_mblock_m: 10
  reduced_ublock_rt: 2
  reduced_mblock_n: 3
  reduced_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_mblock_m: 10
  in_mblock_n: 3
  in_ublock_rt: 2
  in_ublock_ct: 1
  in_data_format: 'Int8'
  out_data_format: 'Int8'
  dest_accumulate_data_format: 'Int32'
  in_dram_buffers: '[[3, 0x20dae960], [2, 0x215a0f80], [5, 0x21d935a0], [3, 0x22585bc0], [2, 0x22d781e0], [4, 0x2356a800], [2, 0x23d5ce20], [1, 0x2454f440], [3, 0x24d41a60], [0, 0x25534080]]'
  target_device: 0
  input_count: 1
  reduce_type: max
  reduce_dim: z
  reduce_z_dim: ',z: 2'
  grid_loc_x: 2
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose: 
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x27865fc0], [2, 0x27c5f2e0], [5, 0x28058600], [3, 0x28451920], [2, 0x2884ac40], [4, 0x28c43f60], [2, 0x2903d280], [1, 0x294365a0], [3, 0x2982f8c0], [0, 0x29c28be0]]'
  out_grid_size_x: 2
  out_grid_size_y: 5
  out_mblock_m: 10
  out_mblock_n: 3
  out_ublock_rt: 2
  out_ublock_ct: 1
  out_t: 31
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  comparison_config_tile_dim_r: 32
  comparison_config_tile_dim_c: 32
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
