#ntb_random_seed=0
#Test id=0
- device: GRAYSKULL
  device_count: 2
  entries: 16
  e2e_entries: 16
  grid_size_x: 2
  grid_size_y: 6
  t: 2
  mblock_m: 1
  mblock_n: 2
  ublock_rt: 1
  ublock_ct: 4
  in_mblock_m: 1
  in_mblock_n: 8
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Float16'
  in_dram_buffers: '[[0, 0x31a758e0], [0, 0x31af7900], [0, 0x31b79920], [0, 0x31bfb940], [0, 0x31c7d960], [0, 0x31cff980], [0, 0x31d819a0], [0, 0x31e039c0], [0, 0x31e859e0], [0, 0x31f07a00], [0, 0x31f89a20], [0, 0x3200ba40]]'
  in_target_device: 0
  e2e_0_dram_buffers: '[[0, 0x32aa9ba0], [0, 0x32b2bbc0], [0, 0x32badbe0], [0, 0x32c2fc00], [0, 0x32cb1c20], [0, 0x32d33c40], [0, 0x32db5c60], [0, 0x32e37c80], [0, 0x32eb9ca0], [0, 0x32f3bcc0], [0, 0x32fbdce0], [0, 0x3303fd00]]'
  dest_accumulate_data_format: 'Float16'
  out_data_format: 'Bfp8'
  op_0_target_device: 0
  op_1_target_device: 0
  input_count: 2
  op_0_grid_loc_x: 0
  op_0_grid_loc_y: 4
  op_1_grid_loc_x: 4
  op_1_grid_loc_y: 1
  grid_loc_x: 0
  grid_loc_y: 4
  math_fidelity: HiFi2
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3561a380], [0, 0x356603a0], [0, 0x356a63c0], [0, 0x356ec3e0], [0, 0x35732400], [0, 0x35778420], [0, 0x357be440], [0, 0x35804460], [0, 0x3584a480], [0, 0x358904a0], [0, 0x358d64c0], [0, 0x3591c4e0]]'
  out_target_device: 0
  out_grid_size_x: 2
  out_grid_size_y: 6
  out_mblock_m: 1
  out_mblock_n: 2
  out_ublock_rt: 1
  out_ublock_ct: 4
  # Program vars
  loop_count: 4
  queue_wrap_size: 32
  e2e_queue_wrap_size: 32
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.85
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-1.0'
  stimulus_config_uniform_upper_bound: '1.0'
#Test id=1
- device: GRAYSKULL
  device_count: 2
  entries: 6
  e2e_entries: 12
  grid_size_x: 1
  grid_size_y: 2
  t: 20
  mblock_m: 1
  mblock_n: 11
  ublock_rt: 5
  ublock_ct: 1
  in_mblock_m: 5
  in_mblock_n: 11
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Float16_b'
  in_dram_buffers: '[[0, 0x30b2ccc0], [0, 0x318445e0]]'
  in_target_device: 1
  e2e_0_dram_buffers: '[[0, 0x34695000], [0, 0x360c4220]]'
  dest_accumulate_data_format: 'Float16'
  out_data_format: 'Float32'
  op_0_target_device: 1
  op_1_target_device: 0
  input_count: 1
  op_0_grid_loc_x: 6
  op_0_grid_loc_y: 1
  op_1_grid_loc_x: 9
  op_1_grid_loc_y: 1
  grid_loc_x: 6
  grid_loc_y: 1
  math_fidelity: HiFi3
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x39016020]]'
  out_target_device: 0
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 10
  out_mblock_n: 11
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 6
  queue_wrap_size: 12
  e2e_queue_wrap_size: 24
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-1.0'
  stimulus_config_uniform_upper_bound: '1.0'
#Test id=2
- device: GRAYSKULL
  device_count: 2
  entries: 24
  e2e_entries: 24
  grid_size_x: 1
  grid_size_y: 1
  t: 12
  mblock_m: 3
  mblock_n: 16
  ublock_rt: 1
  ublock_ct: 2
  in_mblock_m: 3
  in_mblock_n: 32
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Float16'
  in_dram_buffers: '[[0, 0x3359e8a0]]'
  in_target_device: 1
  e2e_0_dram_buffers: '[[0, 0x382ade00]]'
  dest_accumulate_data_format: 'Float16'
  out_data_format: 'Float16'
  op_0_target_device: 1
  op_1_target_device: 1
  input_count: 12
  op_0_grid_loc_x: 7
  op_0_grid_loc_y: 9
  op_1_grid_loc_x: 9
  op_1_grid_loc_y: 3
  grid_loc_x: 7
  grid_loc_y: 9
  math_fidelity: HiFi2
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3c740b40]]'
  out_target_device: 1
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 3
  out_mblock_n: 32
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 48
  e2e_queue_wrap_size: 48
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-1.0'
  stimulus_config_uniform_upper_bound: '1.0'
#Test id=3
- device: GRAYSKULL
  device_count: 2
  entries: 32
  e2e_entries: 16
  grid_size_x: 1
  grid_size_y: 9
  t: 1
  mblock_m: 2
  mblock_n: 2
  ublock_rt: 1
  ublock_ct: 5
  in_mblock_m: 2
  in_mblock_n: 10
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Float16_b'
  in_dram_buffers: '[[0, 0x3c80aac0], [0, 0x3c94fae0], [0, 0x3ca94b00], [0, 0x3cbd9b20], [0, 0x3cd1eb40], [0, 0x3ce63b60], [0, 0x3cfa8b80], [0, 0x3d0edba0], [0, 0x3d232bc0]]'
  in_target_device: 1
  e2e_0_dram_buffers: '[[0, 0x3e601de0], [0, 0x3e6a4600], [0, 0x3e746e20], [0, 0x3e7e9640], [0, 0x3e88be60], [0, 0x3e92e680], [0, 0x3e9d0ea0], [0, 0x3ea736c0], [0, 0x3eb15ee0]]'
  dest_accumulate_data_format: 'Float16'
  out_data_format: 'Bfp8_b'
  op_0_target_device: 1
  op_1_target_device: 1
  input_count: 4
  op_0_grid_loc_x: 0
  op_0_grid_loc_y: 0
  op_1_grid_loc_x: 1
  op_1_grid_loc_y: 0
  grid_loc_x: 0
  grid_loc_y: 0
  math_fidelity: HiFi2
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3ecb9a00], [0, 0x3ed68a20], [0, 0x3ee17a40], [0, 0x3eec6a60], [0, 0x3ef75a80], [0, 0x3f024aa0], [0, 0x3f0d3ac0], [0, 0x3f182ae0], [0, 0x3f231b00]]'
  out_target_device: 1
  out_grid_size_x: 1
  out_grid_size_y: 9
  out_mblock_m: 2
  out_mblock_n: 2
  out_ublock_rt: 1
  out_ublock_ct: 5
  # Program vars
  loop_count: 4
  queue_wrap_size: 64
  e2e_queue_wrap_size: 32
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.85
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-1.0'
  stimulus_config_uniform_upper_bound: '1.0'
#Test id=4
- device: GRAYSKULL
  device_count: 2
  entries: 64
  e2e_entries: 32
  grid_size_x: 2
  grid_size_y: 5
  t: 2
  mblock_m: 4
  mblock_n: 2
  ublock_rt: 4
  ublock_ct: 1
  in_mblock_m: 16
  in_mblock_n: 2
  in_ublock_rt: 1
  in_ublock_ct: 1
  in_data_format: 'Bfp8_b'
  in_dram_buffers: '[[0, 0x3091ab20], [0, 0x30d7ab40], [0, 0x311dab60], [0, 0x3163ab80], [0, 0x31a9aba0], [0, 0x31efabc0], [0, 0x3235abe0], [0, 0x327bac00], [0, 0x32c1ac20], [0, 0x3307ac40]]'
  in_target_device: 0
  e2e_0_dram_buffers: '[[0, 0x337c2600], [0, 0x339f2620], [0, 0x33c22640], [0, 0x33e52660], [0, 0x34082680], [0, 0x342b26a0], [0, 0x344e26c0], [0, 0x347126e0], [0, 0x34942700], [0, 0x34b72720]]'
  dest_accumulate_data_format: 'Float16'
  out_data_format: 'Float32'
  op_0_target_device: 0
  op_1_target_device: 1
  input_count: 4
  op_0_grid_loc_x: 1
  op_0_grid_loc_y: 5
  op_1_grid_loc_x: 7
  op_1_grid_loc_y: 1
  grid_loc_x: 1
  grid_loc_y: 5
  math_fidelity: HiFi3
  untilize_output:  'true'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x34eadca0]]'
  out_target_device: 1
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 80
  out_mblock_n: 4
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 8
  queue_wrap_size: 128
  e2e_queue_wrap_size: 64
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.90
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-1.0'
  stimulus_config_uniform_upper_bound: '1.0'
