#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 4
  grid_size_y: 3
  in1_grid_size_x: 4
  in1_grid_size_y: 3
  input_q_t: 2
  output_q_t: 2
  mblock_m: 4
  mblock_n: 4
  mblock_k: 3
  ublock_rt: 3
  ublock_ct: 1
  ublock_kt: 2
  in_0_tile_dim_r: 4
  in_0_tile_dim_c: 32
  in1_mblock_n: 4
  in1_mblock_k: 4
  in1_ublock_ct: 1
  in1_ublock_kt: 2
  in_1_tile_dim_r: 1
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 12
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: none
  out_data_format: 'Bfp8_b'
  intermed_data_format: 'Float16_b'
  in0_data_format: 'Bfp4_b'
  in0_dram_buffers: '[[4, 0x1b6a6fa0], [4, 0x1b6fc7c0], [1, 0x1b751fe0], [4, 0x1b7a7800], [0, 0x1b7fd020], [3, 0x1b852840], [0, 0x1b8a8060], [0, 0x1b8fd880], [5, 0x1b9530a0], [3, 0x1b9a88c0], [3, 0x1b9fe0e0], [1, 0x1ba53900]]'
  in1_data_format: 'Bfp8_b'
  in1_dram_buffers: '[[4, 0x1ca10320], [4, 0x1ca56340], [1, 0x1ca9c360], [4, 0x1cae2380], [0, 0x1cb283a0], [3, 0x1cb6e3c0], [0, 0x1cbb43e0], [0, 0x1cbfa400], [5, 0x1cc40420], [3, 0x1cc86440], [3, 0x1cccc460], [1, 0x1cd12480]]'
  in2_data_format: 'Bfp8_b'
  in2_dram_buffers: '[[4, 0x22943460], [4, 0x229ac480], [1, 0x22a154a0], [4, 0x22a7e4c0]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'math'
  relu_en: ' true'
  relu_mode: 'max'
  relu_threshold: '0.700000'
  z: 1
  min_buffer_input: 0
  target_device: 0
  input_count: 2
  grid_loc_x: 2
  grid_loc_y: 4
  math_fidelity: HiFi2
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x2b665a00], [4, 0x2b6cea20], [1, 0x2b737a40], [4, 0x2b7a0a60], [0, 0x2b809a80], [3, 0x2b872aa0], [0, 0x2b8dbac0], [0, 0x2b944ae0], [5, 0x2b9adb00], [3, 0x2ba16b20], [3, 0x2ba7fb40], [1, 0x2bae8b60]]'
  out_grid_size_x: 4
  out_grid_size_y: 3
  out_mblock_m: 4
  out_mblock_n: 4
  out_ublock_rt: 3
  out_ublock_ct: 1
  out_tile_dim_r: 1
  out_tile_dim_c: 32
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.4
  comparison_config_check_pcc: 0.9
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 6
  grid_size_y: 6
  in1_grid_size_x: 6
  in1_grid_size_y: 6
  input_q_t: 2
  output_q_t: 2
  mblock_m: 1
  mblock_n: 3
  mblock_k: 3
  ublock_rt: 1
  ublock_ct: 6
  ublock_kt: 2
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 3
  in1_mblock_k: 3
  in1_ublock_ct: 6
  in1_ublock_kt: 2
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 18
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Bfp8_b'
  intermed_data_format: 'Float16_b'
  in0_data_format: 'Bfp8_b'
  in0_dram_buffers: '[[5, 0x219d4540], [1, 0x219ee960], [4, 0x21a08d80], [0, 0x21a231a0], [5, 0x21a3d5c0], [4, 0x21a579e0], [0, 0x21a71e00], [0, 0x21a8c220], [1, 0x21aa6640], [3, 0x21ac0a60], [3, 0x21adae80], [2, 0x21af52a0], [3, 0x21b0f6c0], [0, 0x21b29ae0], [2, 0x21b43f00], [4, 0x21b5e320], [2, 0x21b78740], [2, 0x21b92b60], [4, 0x21bacf80], [5, 0x21bc73a0], [1, 0x21be17c0], [1, 0x21bfbbe0], [3, 0x21c16000], [5, 0x21c30420], [5, 0x21c4a840], [0, 0x21c64c60], [5, 0x21c7f080], [1, 0x21c994a0], [3, 0x21cb38c0], [5, 0x21ccdce0], [0, 0x21ce8100], [1, 0x21d02520], [5, 0x21d1c940], [4, 0x21d36d60], [3, 0x21d51180], [5, 0x21d6b5a0]]'
  in1_data_format: 'Bfp4_b'
  in1_dram_buffers: '[[5, 0x25221840], [1, 0x25322060], [4, 0x25422880], [0, 0x255230a0], [5, 0x256238c0], [4, 0x257240e0], [0, 0x25824900], [0, 0x25925120], [1, 0x25a25940], [3, 0x25b26160], [3, 0x25c26980], [2, 0x25d271a0], [3, 0x25e279c0], [0, 0x25f281e0], [2, 0x26028a00], [4, 0x26129220], [2, 0x26229a40], [2, 0x2632a260], [4, 0x2642aa80], [5, 0x2652b2a0], [1, 0x2662bac0], [1, 0x2672c2e0], [3, 0x2682cb00], [5, 0x2692d320], [5, 0x26a2db40], [0, 0x26b2e360], [5, 0x26c2eb80], [1, 0x26d2f3a0], [3, 0x26e2fbc0], [5, 0x26f303e0], [0, 0x27030c00], [1, 0x27131420], [5, 0x27231c40], [4, 0x27332460], [3, 0x27432c80], [5, 0x275334a0]]'
  in2_data_format: 'Float32'
  in2_dram_buffers: '[[5, 0x29d33ac0], [1, 0x29e55ee0], [4, 0x29f78300], [0, 0x2a09a720], [5, 0x2a1bcb40], [4, 0x2a2def60]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'gelu'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'min'
  relu_threshold: '0.000000'
  z: 1
  min_buffer_input: 0
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 2
  math_fidelity: HiFi3
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x3660b760], [1, 0x3665a380], [4, 0x366a8fa0], [0, 0x366f7bc0], [5, 0x367467e0], [4, 0x36795400], [0, 0x367e4020], [0, 0x36832c40], [1, 0x36881860], [3, 0x368d0480], [3, 0x3691f0a0], [2, 0x3696dcc0], [3, 0x369bc8e0], [0, 0x36a0b500], [2, 0x36a5a120], [4, 0x36aa8d40], [2, 0x36af7960], [2, 0x36b46580], [4, 0x36b951a0], [5, 0x36be3dc0], [1, 0x36c329e0], [1, 0x36c81600], [3, 0x36cd0220], [5, 0x36d1ee40], [5, 0x36d6da60], [0, 0x36dbc680], [5, 0x36e0b2a0], [1, 0x36e59ec0], [3, 0x36ea8ae0], [5, 0x36ef7700], [0, 0x36f46320], [1, 0x36f94f40], [5, 0x36fe3b60], [4, 0x37032780], [3, 0x370813a0], [5, 0x370cffc0]]'
  out_grid_size_x: 6
  out_grid_size_y: 6
  out_mblock_m: 1
  out_mblock_n: 3
  out_ublock_rt: 1
  out_ublock_ct: 6
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.4
  comparison_config_check_pcc: 0.9
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 4
  grid_size_y: 3
  in1_grid_size_x: 4
  in1_grid_size_y: 3
  input_q_t: 4
  output_q_t: 4
  mblock_m: 2
  mblock_n: 2
  mblock_k: 3
  ublock_rt: 5
  ublock_ct: 1
  ublock_kt: 2
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 2
  in1_mblock_k: 4
  in1_ublock_ct: 1
  in1_ublock_kt: 2
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 1
  in_2_tile_dim_c: 32
  m_k: 12
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Float16_b'
  intermed_data_format: 'Float16_b'
  in0_data_format: 'Float32'
  in0_dram_buffers: '[[4, 0x33a5dac0], [5, 0x341ecae0], [5, 0x3497bb00], [0, 0x3510ab20], [2, 0x35899b40], [1, 0x36028b60], [3, 0x367b7b80], [1, 0x36f46ba0], [0, 0x376d5bc0], [2, 0x37e64be0], [4, 0x385f3c00], [2, 0x38d82c20]]'
  in1_data_format: 'Float32'
  in1_dram_buffers: '[[4, 0x3a4bb0a0], [5, 0x3a6bf0c0], [5, 0x3a8c30e0], [0, 0x3aac7100], [2, 0x3accb120], [1, 0x3aecf140], [3, 0x3b0d3160], [1, 0x3b2d7180], [0, 0x3b4db1a0], [2, 0x3b6df1c0], [4, 0x3b8e31e0], [2, 0x3bae7200]]'
  in2_data_format: 'Bfp8_b'
  in2_dram_buffers: '[[4, 0x3c7e3e20], [5, 0x3c892e40], [5, 0x3c941e60], [0, 0x3c9f0e80]]'
  dest_accumulate_data_format: 'Float16'
  sfpu_op: 'gelu'
  sfpu_execution_thread: 'math'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 1
  min_buffer_input: 1
  target_device: 0
  input_count: 4
  grid_loc_x: 1
  grid_loc_y: 4
  math_fidelity: HiFi3
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[4, 0x3ecc79e0], [5, 0x3ee0ca00], [5, 0x3ef51a20], [0, 0x3f096a40], [2, 0x3f1dba60], [1, 0x3f320a80], [3, 0x3f465aa0], [1, 0x3f5aaac0], [0, 0x3f6efae0], [2, 0x3f834b00], [4, 0x3f979b20], [2, 0x3fabeb40]]'
  out_grid_size_x: 4
  out_grid_size_y: 3
  out_mblock_m: 2
  out_mblock_n: 2
  out_ublock_rt: 5
  out_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 1
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.4
  comparison_config_check_pcc: 0.9
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-2.0'
  stimulus_config_uniform_upper_bound: '2.0'
