#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 5
  in1_grid_size_x: 1
  in1_grid_size_y: 5
  input_q_t: 46
  output_q_t: 23
  mblock_m: 1
  mblock_n: 1
  mblock_k: 5
  ublock_rt: 3
  ublock_ct: 1
  ublock_kt: 2
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 1
  in1_ublock_ct: 1
  in1_ublock_kt: 2
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 5
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x2195e880], [0, 0x225294a0], [4, 0x230f40c0], [1, 0x23cbece0], [4, 0x24889900]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x28917b00], [0, 0x289e0f20], [4, 0x28aaa340], [1, 0x28b73760], [4, 0x28c3cb80]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[0, 0x2aaedce0]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 2
  min_buffer_input: 0
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3dbad040], [0, 0x3dc43f60], [4, 0x3dcdae80], [1, 0x3dd71da0], [4, 0x3de08cc0]]'
  out_grid_size_x: 1
  out_grid_size_y: 5
  out_mblock_m: 1
  out_mblock_n: 1
  out_ublock_rt: 3
  out_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.4
  comparison_config_check_pcc: 0.9
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 6
  in1_grid_size_x: 1
  in1_grid_size_y: 6
  input_q_t: 10
  output_q_t: 5
  mblock_m: 1
  mblock_n: 5
  mblock_k: 12
  ublock_rt: 1
  ublock_ct: 1
  ublock_kt: 10
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 5
  in1_mblock_k: 2
  in1_ublock_ct: 1
  in1_ublock_kt: 10
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 12
  u_kt: 10
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int32'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x251fe9a0], [5, 0x2571f1c0], [5, 0x25c3f9e0], [2, 0x26160200], [5, 0x26680a20], [1, 0x26ba1240]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x2fa6af20], [5, 0x2feb0b40], [5, 0x302f6760], [2, 0x3073c380], [5, 0x30b81fa0], [1, 0x30fc7bc0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x3b9c5240]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'math'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 2
  min_buffer_input: 1
  target_device: 0
  input_count: 2
  grid_loc_x: 7
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x3cb30480], [5, 0x3cb95120], [5, 0x3cbf9dc0], [2, 0x3cc5ea60], [5, 0x3ccc3700], [1, 0x3cd283a0]]'
  out_grid_size_x: 1
  out_grid_size_y: 6
  out_mblock_m: 1
  out_mblock_n: 5
  out_ublock_rt: 1
  out_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0
  comparison_config_check_pcc: 0.8
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 2
  grid_size_y: 1
  in1_grid_size_x: 2
  in1_grid_size_y: 1
  input_q_t: 38
  output_q_t: 2
  mblock_m: 4
  mblock_n: 1
  mblock_k: 2
  ublock_rt: 2
  ublock_ct: 2
  ublock_kt: 6
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 4
  in1_ublock_ct: 2
  in1_ublock_kt: 6
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 4
  u_kt: 6
  l1_acc: false
  stoch_rnd_mode: all
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x37330260], [5, 0x3925c280]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x3b9c50a0], [5, 0x3c95b0c0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x3d8f4740], [5, 0x3ec1a760]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'min'
  relu_threshold: '0.000000'
  z: 19
  min_buffer_input: 1
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 1}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x3ff47d00], [5, 0x3ff8dd20]]'
  out_grid_size_x: 2
  out_grid_size_y: 1
  out_mblock_m: 4
  out_mblock_n: 1
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0
  comparison_config_check_pcc: 0.8
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
