#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 1
  grid_size_y: 5
  in1_grid_size_x: 1
  in1_grid_size_y: 5
  input_q_t: 46
  output_q_t: 46
  mblock_m: 1
  mblock_n: 1
  mblock_k: 5
  ublock_rt: 3
  ublock_ct: 1
  ublock_kt: 2
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 1
  in1_ublock_ct: 1
  in1_ublock_kt: 2
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 5
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x20276d20], [0, 0x20e41940], [4, 0x21a0c560], [1, 0x225d7180], [4, 0x231a1da0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x23e24a40], [0, 0x23eede60], [4, 0x23fb7280], [1, 0x240806a0], [4, 0x24149ac0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[0, 0x259a9660]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 0
  target_device: 0
  input_count: 2
  grid_loc_x: 6
  grid_loc_y: 1
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 15}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x3db17e20], [0, 0x3dc45c40], [4, 0x3dd73a60], [1, 0x3dea1880], [4, 0x3dfcf6a0]]'
  out_grid_size_x: 1
  out_grid_size_y: 5
  out_mblock_m: 1
  out_mblock_n: 1
  out_ublock_rt: 3
  out_ublock_ct: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.55
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  in1_grid_size_x: 1
  in1_grid_size_y: 1
  input_q_t: 50
  output_q_t: 50
  mblock_m: 2
  mblock_n: 1
  mblock_k: 16
  ublock_rt: 1
  ublock_ct: 2
  ublock_kt: 1
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 16
  in1_ublock_ct: 2
  in1_ublock_kt: 1
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 16
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int32'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x35bb3640]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x36537d00]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x3bace3e0]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'math'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 1
  target_device: 0
  input_count: 2
  grid_loc_x: 7
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 2}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x3cfcc520]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 2
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.7
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 8
  grid_size_x: 2
  grid_size_y: 1
  in1_grid_size_x: 2
  in1_grid_size_y: 1
  input_q_t: 14
  output_q_t: 14
  mblock_m: 1
  mblock_n: 1
  mblock_k: 2
  ublock_rt: 2
  ublock_ct: 2
  ublock_kt: 10
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 4
  in1_ublock_ct: 2
  in1_ublock_kt: 10
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 4
  u_kt: 10
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x263ecaa0], [5, 0x268b5ac0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x2b0b5e80], [5, 0x2ba47ea0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x2d3a8560], [5, 0x2d56bd80]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'min'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 1
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 5
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 2}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x31c91480], [5, 0x31d0bca0]]'
  out_grid_size_x: 2
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 1
  out_ublock_rt: 2
  out_ublock_ct: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 16
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.55
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 2
  grid_size_y: 7
  in1_grid_size_x: 2
  in1_grid_size_y: 7
  input_q_t: 8
  output_q_t: 8
  mblock_m: 13
  mblock_n: 1
  mblock_k: 7
  ublock_rt: 1
  ublock_ct: 4
  ublock_kt: 2
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 1
  in1_mblock_k: 2
  in1_ublock_ct: 4
  in1_ublock_kt: 2
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 14
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x2f1d97c0], [0, 0x2f811fe0], [5, 0x2fe4a800], [0, 0x30483020], [4, 0x30abb840], [5, 0x310f4060], [0, 0x3172c880], [3, 0x31d650a0], [1, 0x3239d8c0], [3, 0x329d60e0], [5, 0x3300e900], [3, 0x33647120], [2, 0x33c7f940], [3, 0x342b8160]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x35181f20], [0, 0x3520df40], [5, 0x35299f60], [0, 0x35325f80], [4, 0x353b1fa0], [5, 0x3543dfc0], [0, 0x354c9fe0], [3, 0x35556000], [1, 0x355e2020], [3, 0x3566e040], [5, 0x356fa060], [3, 0x35786080], [2, 0x358120a0], [3, 0x3589e0c0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x3606df00], [0, 0x366faf20]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 0
  target_device: 0
  input_count: 1
  grid_loc_x: 6
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 91}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x3c3cfbe0], [0, 0x3c596c00], [5, 0x3c75dc20], [0, 0x3c924c40], [4, 0x3caebc60], [5, 0x3ccb2c80], [0, 0x3ce79ca0], [3, 0x3d040cc0], [1, 0x3d207ce0], [3, 0x3d3ced00], [5, 0x3d595d20], [3, 0x3d75cd40], [2, 0x3d923d60], [3, 0x3daead80]]'
  out_grid_size_x: 2
  out_grid_size_y: 7
  out_mblock_m: 13
  out_mblock_n: 1
  out_ublock_rt: 1
  out_ublock_ct: 4
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.55
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 5
  in1_grid_size_x: 1
  in1_grid_size_y: 5
  input_q_t: 12
  output_q_t: 12
  mblock_m: 2
  mblock_n: 8
  mblock_k: 5
  ublock_rt: 1
  ublock_ct: 4
  ublock_kt: 5
  in_0_tile_dim_r: 32
  in_0_tile_dim_c: 32
  in1_mblock_n: 8
  in1_mblock_k: 1
  in1_ublock_ct: 4
  in1_ublock_kt: 5
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  in_2_tile_dim_r: 32
  in_2_tile_dim_c: 32
  m_k: 5
  u_kt: 5
  l1_acc: false
  stoch_rnd_mode: fpu
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[2, 0x36af48a0], [4, 0x36d84cc0], [2, 0x370150e0], [1, 0x372a5500], [3, 0x37535920]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[2, 0x37c4a940], [4, 0x3847e960], [2, 0x38cb2980], [1, 0x394e69a0], [3, 0x39d1a9c0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[2, 0x3a7772e0]]'
  dest_accumulate_data_format: 'Int32'
  sfpu_op: 'invalid'
  sfpu_execution_thread: 'pack'
  relu_en: 'false'
  relu_mode: 'max'
  relu_threshold: '0.000000'
  z: 0
  min_buffer_input: 0
  target_device: 0
  input_count: 1
  grid_loc_x: 6
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output: 'false'
  transpose_in1:            
  bcast_in2: '[broadcast: {r: 10}]'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[2, 0x3ea1a900], [4, 0x3ed62920], [2, 0x3f0aa940], [1, 0x3f3f2960], [3, 0x3f73a980]]'
  out_grid_size_x: 1
  out_grid_size_y: 5
  out_mblock_m: 2
  out_mblock_n: 8
  out_ublock_rt: 1
  out_ublock_ct: 4
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.15
  comparison_config_check_pct: 0.55
  comparison_config_check_pcc: 0.99
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
