#ntb_random_seed=0
#Test id=0
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 5
  grid_size_y: 7
  t: 1
  mblock_m: 12
  mblock_n: 2
  mblock_k: 181
  ublock_rt: 2
  ublock_ct: 1
  ublock_kt: 2
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  m_k: 181
  u_kt: 2
  l1_acc: false
  stoch_rnd_mode: all
  num_sparse_tiles: 128
  num_index_tiles: 16
  sparse_tile_ptr_bits: 8
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[1, 0x16383ca0], [4, 0x1640fcc0], [3, 0x1649bce0], [4, 0x16527d00], [5, 0x165b3d20], [0, 0x1663fd40], [0, 0x166cbd60]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[1, 0x178237c0], [4, 0x17b3b5e0], [3, 0x17e53400], [4, 0x1816b220], [5, 0x18483040]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[1, 0x24ddf120], [4, 0x24e1f940], [3, 0x24e60160], [4, 0x24ea0980], [5, 0x24ee11a0], [0, 0x24f219c0], [0, 0x24f621e0]]'
  dest_accumulate_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 1
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[1, 0x3dfada80], [4, 0x3dfe22a0], [3, 0x3e016ac0], [4, 0x3e04b2e0], [5, 0x3e07fb00], [0, 0x3e0b4320], [0, 0x3e0e8b40], [0, 0x3e11d360], [4, 0x3e151b80], [1, 0x3e1863a0], [4, 0x3e1babc0], [3, 0x3e1ef3e0], [1, 0x3e223c00], [4, 0x3e258420], [4, 0x3e28cc40], [2, 0x3e2c1460], [1, 0x3e2f5c80], [5, 0x3e32a4a0], [2, 0x3e35ecc0], [5, 0x3e3934e0], [2, 0x3e3c7d00], [2, 0x3e3fc520], [4, 0x3e430d40], [4, 0x3e465560], [2, 0x3e499d80], [1, 0x3e4ce5a0], [1, 0x3e502dc0], [3, 0x3e5375e0], [0, 0x3e56be00], [0, 0x3e5a0620], [4, 0x3e5d4e40], [0, 0x3e609660], [3, 0x3e63de80], [2, 0x3e6726a0], [2, 0x3e6a6ec0]]'
  out_grid_size_x: 5
  out_grid_size_y: 7
  out_mblock_m: 12
  out_mblock_n: 2
  out_ublock_rt: 2
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.0
  comparison_config_check_pcc: 0.90
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=1
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 1
  grid_size_y: 1
  t: 1
  mblock_m: 5
  mblock_n: 4
  mblock_k: 241
  ublock_rt: 3
  ublock_ct: 1
  ublock_kt: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  m_k: 241
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: all
  num_sparse_tiles: 128
  num_index_tiles: 16
  sparse_tile_ptr_bits: 8
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[3, 0x3ccc7fc0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[3, 0x3dc1dac0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[3, 0x3f542e60]]'
  dest_accumulate_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 2
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[3, 0x3f627b80]]'
  out_grid_size_x: 1
  out_grid_size_y: 1
  out_mblock_m: 5
  out_mblock_n: 4
  out_ublock_rt: 3
  out_ublock_ct: 1
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.0
  comparison_config_check_pcc: 0.90
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=2
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 8
  grid_size_y: 8
  t: 1
  mblock_m: 6
  mblock_n: 11
  mblock_k: 207
  ublock_rt: 1
  ublock_ct: 1
  ublock_kt: 1
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  m_k: 207
  u_kt: 1
  l1_acc: false
  stoch_rnd_mode: pack
  num_sparse_tiles: 128
  num_index_tiles: 16
  sparse_tile_ptr_bits: 8
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[5, 0x18b4a000], [2, 0x18bd6020], [5, 0x18c62040], [4, 0x18cee060], [2, 0x18d7a080], [2, 0x18e060a0], [3, 0x18e920c0], [5, 0x18f1e0e0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[5, 0x1a0b8460], [2, 0x1aa72c00], [5, 0x1b42d3a0], [4, 0x1bde7b40], [2, 0x1c7a22e0], [2, 0x1d15ca80], [3, 0x1db17220], [5, 0x1e4d19c0]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[5, 0x337ef8c0], [2, 0x338300e0], [5, 0x33870900], [4, 0x338b1120], [2, 0x338f1940], [2, 0x33932160], [3, 0x33972980], [5, 0x339b31a0]]'
  dest_accumulate_data_format: 'Int32'
  target_device: 0
  input_count: 2
  grid_loc_x: 0
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[5, 0x3aa193a0], [2, 0x3aa616c0], [5, 0x3aaa99e0], [4, 0x3aaf1d00], [2, 0x3ab3a020], [2, 0x3ab82340], [3, 0x3abca660], [5, 0x3ac12980], [5, 0x3ac5aca0], [1, 0x3aca2fc0], [1, 0x3aceb2e0], [2, 0x3ad33600], [5, 0x3ad7b920], [3, 0x3adc3c40], [2, 0x3ae0bf60], [0, 0x3ae54280], [4, 0x3ae9c5a0], [0, 0x3aee48c0], [2, 0x3af2cbe0], [0, 0x3af74f00], [4, 0x3afbd220], [2, 0x3b005540], [3, 0x3b04d860], [3, 0x3b095b80], [2, 0x3b0ddea0], [1, 0x3b1261c0], [2, 0x3b16e4e0], [4, 0x3b1b6800], [4, 0x3b1feb20], [1, 0x3b246e40], [4, 0x3b28f160], [1, 0x3b2d7480], [2, 0x3b31f7a0], [3, 0x3b367ac0], [3, 0x3b3afde0], [4, 0x3b3f8100], [1, 0x3b440420], [0, 0x3b488740], [2, 0x3b4d0a60], [0, 0x3b518d80], [0, 0x3b5610a0], [4, 0x3b5a93c0], [2, 0x3b5f16e0], [3, 0x3b639a00], [3, 0x3b681d20], [2, 0x3b6ca040], [5, 0x3b712360], [0, 0x3b75a680], [3, 0x3b7a29a0], [0, 0x3b7eacc0], [5, 0x3b832fe0], [4, 0x3b87b300], [1, 0x3b8c3620], [0, 0x3b90b940], [4, 0x3b953c60], [0, 0x3b99bf80], [4, 0x3b9e42a0], [1, 0x3ba2c5c0], [3, 0x3ba748e0], [0, 0x3babcc00], [0, 0x3bb04f20], [3, 0x3bb4d240], [3, 0x3bb95560], [2, 0x3bbdd880]]'
  out_grid_size_x: 8
  out_grid_size_y: 8
  out_mblock_m: 6
  out_mblock_n: 11
  out_ublock_rt: 1
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.0
  comparison_config_check_pcc: 0.90
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=3
- device: WORMHOLE_B0
  entries: 2
  grid_size_x: 1
  grid_size_y: 8
  t: 54
  mblock_m: 1
  mblock_n: 13
  mblock_k: 54
  ublock_rt: 2
  ublock_ct: 1
  ublock_kt: 6
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  m_k: 54
  u_kt: 6
  l1_acc: false
  stoch_rnd_mode: all
  num_sparse_tiles: 128
  num_index_tiles: 16
  sparse_tile_ptr_bits: 8
  out_data_format: 'Int8'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[1, 0x17bebec0], [2, 0x17c31ee0], [3, 0x17c77f00], [5, 0x17cbdf20], [3, 0x17d03f40], [4, 0x17d49f60], [3, 0x17d8ff80], [0, 0x17dd5fa0]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[1, 0x1a338760]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[1, 0x3926dde0], [2, 0x3928e200], [3, 0x392ae620], [5, 0x392cea40], [3, 0x392eee60], [4, 0x3930f280], [3, 0x3932f6a0], [0, 0x3934fac0]]'
  dest_accumulate_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 4
  grid_loc_y: 0
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[1, 0x3df39a40], [2, 0x3e239760], [3, 0x3e539480], [5, 0x3e8391a0], [3, 0x3eb38ec0], [4, 0x3ee38be0], [3, 0x3f138900], [0, 0x3f438620]]'
  out_grid_size_x: 1
  out_grid_size_y: 8
  out_mblock_m: 1
  out_mblock_n: 13
  out_ublock_rt: 2
  out_ublock_ct: 1
  # Program vars
  loop_count: 1
  queue_wrap_size: 4
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.0
  comparison_config_check_pcc: 0.90
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
#Test id=4
- device: WORMHOLE_B0
  entries: 4
  grid_size_x: 2
  grid_size_y: 1
  t: 2
  mblock_m: 1
  mblock_n: 6
  mblock_k: 180
  ublock_rt: 1
  ublock_ct: 3
  ublock_kt: 7
  out_tile_dim_r: 32
  out_tile_dim_c: 32
  in_1_tile_dim_r: 32
  in_1_tile_dim_c: 32
  m_k: 180
  u_kt: 7
  l1_acc: false
  stoch_rnd_mode: none
  num_sparse_tiles: 128
  num_index_tiles: 16
  sparse_tile_ptr_bits: 8
  out_data_format: 'Int32'
  intermed_data_format: 'Int32'
  in0_data_format: 'Int8'
  in0_dram_buffers: '[[0, 0x1676b740]]'
  in1_data_format: 'Int8'
  in1_dram_buffers: '[[0, 0x168ca920], [4, 0x22a97140]]'
  in2_data_format: 'Int32'
  in2_dram_buffers: '[[0, 0x2ee291a0]]'
  dest_accumulate_data_format: 'Int32'
  target_device: 0
  input_count: 1
  grid_loc_x: 6
  grid_loc_y: 2
  math_fidelity: HiFi4
  untilize_output: 'false'
  ublock_order: r
  buf_size_mb: 2
  # Scale output queue grid and mblock size if output is untilized
  # Net2pipe requires grid size 1x1 if untilized output is written to the queue
  out_dram_buffers: '[[0, 0x316c5ca0], [4, 0x31756ec0]]'
  out_grid_size_x: 2
  out_grid_size_y: 1
  out_mblock_m: 1
  out_mblock_n: 6
  out_ublock_rt: 1
  out_ublock_ct: 3
  # Program vars
  loop_count: 2
  queue_wrap_size: 8
  # Test and stimulus config
  comparison_config_type: 'AllCloseHw'
  comparison_config_atol: 0.01
  comparison_config_rtol: 0.30
  comparison_config_check_pct: 0.0
  comparison_config_check_pcc: 0.90
  comparison_config_verbosity: 'Concise'
  stimulus_config_type: 'Uniform'
  stimulus_config_uniform_lower_bound: '-127.0'
  stimulus_config_uniform_upper_bound: '127.0'
