# TODO - Common section to be shred across variants.
# List out all the op variants to be tested
common:
  some: thing
variants:
  tt_eltwise_unary_sfpu_op<SfpuOp::Exp, DstMode::Tile>:
    # Common section for shared configuration for all tests for this op variant
    tests:
      1x1_16tile:
        perf-config:
          perf-test: true
          device-vs-model-en-checker: false
          device-vs-model-cycles-rtol: 1.0
          perf-decouple-modes: [["None"]]
          perf-decouple-op: "target_op"
        rbg-config:
        - perf_lib/ops/rbg_config_single_core_directed_test.yaml
        -
          config:
            max-tensor-dim-r: 4
            min-tensor-dim-r: 4
            max-tensor-dim-c: 4
            min-tensor-dim-c: 4
  tt_eltwise_unary_sfpu_op<SfpuOp::Gelu, DstMode::Tile>:
    tests:
      1x1_16tile:
        perf-config:
          perf-test: true
          device-vs-model-en-checker: false
          device-vs-model-cycles-rtol: 1.0
          perf-decouple-modes: [["None"]]
          perf-decouple-op: "target_op"
        rbg-config:
        - perf_lib/ops/rbg_config_single_core_directed_test.yaml
        -
          config:
            max-tensor-dim-r: 4
            min-tensor-dim-r: 4
            max-tensor-dim-c: 4
            min-tensor-dim-c: 4
  tt_eltwise_unary_sfpu_op<SfpuOp::Reciprocal, DstMode::Tile>:
    tests:
      1x1_16tile:
        perf-config:
          perf-test: true
          device-vs-model-en-checker: false
          device-vs-model-cycles-rtol: 1.0
          perf-decouple-modes: [["None"]]
          perf-decouple-op: "target_op"
        rbg-config:
        - perf_lib/ops/rbg_config_single_core_directed_test.yaml
        -
          config:
            max-tensor-dim-r: 4
            min-tensor-dim-r: 4
            max-tensor-dim-c: 4
            min-tensor-dim-c: 4
  tt_eltwise_unary_sfpu_op<SfpuOp::Sqrt, DstMode::Tile>:
    tests:
      1x1_16tile:
        perf-config:
          perf-test: true
          device-vs-model-en-checker: false
          device-vs-model-cycles-rtol: 1.0
          perf-decouple-modes: [["None"]]
          perf-decouple-op: "target_op"
        rbg-config:
        - perf_lib/ops/rbg_config_single_core_directed_test.yaml
        -
          config:
            max-tensor-dim-r: 4
            min-tensor-dim-r: 4
            max-tensor-dim-c: 4
            min-tensor-dim-c: 4