#Test id=0
- device: BLACKHOLE
  loop_count: 0
  input_count: 0
  target_device: x
  queue_wrap_size: 0
  in0: ''
  stimulus_in0: ''
  queue_settings_in0: ''
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: ''
  queue_settings_out0: ''
  op0: ''
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 0], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 0
  input_count: 0
  target_device: x
  queue_wrap_size: 0
  in0: ''
  stimulus_in0: ''
  queue_settings_in0: ''
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: ''
  queue_settings_out0: ''
  op0: ''
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 0], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 0
  input_count: 0
  target_device: x
  queue_wrap_size: 0
  in0: ''
  stimulus_in0: ''
  queue_settings_in0: ''
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: ''
  queue_settings_out0: ''
  op0: ''
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 0], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 0
  input_count: 0
  target_device: x
  queue_wrap_size: 0
  in0: ''
  stimulus_in0: ''
  queue_settings_in0: ''
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: ''
  queue_settings_out0: ''
  op0: ''
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 0], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 0
  input_count: 0
  target_device: x
  queue_wrap_size: 0
  in0: ''
  stimulus_in0: ''
  queue_settings_in0: ''
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: ''
  queue_settings_out0: ''
  op0: ''
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 0], check_tile_cols_range: [1, 32] }'
