#Test id=0
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [10, 3], ublock: [2, 5], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x12a10b80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 3], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf0aa900]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, m_k: 5, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 1, mblock: [10, 12], ublock: [12, 3], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x168efb40], [0, 0x17bebb80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 1, mblock: [1, 12], ublock: [1, 3], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf3974c0], [0, 0xf3bfd00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 1, mblock: [1, 12], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, m_k: 10, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 30, mblock: [14, 16], ublock: [5, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x18195d40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 30, mblock: [1, 16], ublock: [1, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf3b6ac0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 30, mblock: [1, 16], ublock: [1, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 110, m_k: 14, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 3], t: 1, mblock: [12, 10], ublock: [3, 2], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x36259500], [0, 0x36323d40], [0, 0x363ee580]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 3], t: 4, mblock: [1, 5], ublock: [1, 4], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0x9b3bc80], [0, 0x9b524c0], [0, 0x9b68d00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 3], t: 4, mblock: [1, 5], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 25, stoch_rnd_mode: none, m_k: 9, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, broadcast: {z: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 8], t: 1, mblock: [1, 1], ublock: [7, 10], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x36b34f40], [0, 0x36b83b80], [0, 0x36bd27c0], [0, 0x36c21400], [0, 0x36c70040], [0, 0x36cbec80], [0, 0x36d0d8c0], [0, 0x36d5c500]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 8], t: 2, mblock: [1, 5], ublock: [1, 2], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xe0d2900], [0, 0xe0e9140], [0, 0xe0ff980], [0, 0xe1161c0], [0, 0xe12ca00], [0, 0xe143240], [0, 0xe159a80], [0, 0xe1702c0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 8], t: 2, mblock: [1, 5], ublock: [1, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, stoch_rnd_mode: fpu, m_k: 8, u_kt: 7, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
