#Test id=0
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [5, 10], ublock: [1, 4], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2e1b99c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [5, 1], ublock: [3, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xb19d840]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [5, 1], ublock: [3, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: c, stoch_rnd_mode: none, m_k: 4, u_kt: 10, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [2, 1], t: 1, mblock: [12, 10], ublock: [3, 12], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x168efb40], [0, 0x17bebb80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [2, 1], t: 1, mblock: [12, 1], ublock: [3, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf3974c0], [0, 0xf3bfd00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [2, 1], t: 1, mblock: [12, 1], ublock: [3, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: c, m_k: 10, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 30, mblock: [16, 14], ublock: [1, 5], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x18195d40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 30, mblock: [16, 1], ublock: [1, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf3b6ac0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 30, mblock: [16, 1], ublock: [1, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: c, relu_en: true, relu_mode: max, relu_threshold: 110, m_k: 14, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [3, 1], t: 1, mblock: [2, 13], ublock: [8, 5], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3f7d8240], [0, 0x3f8fca80], [0, 0x3fa212c0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [3, 1], t: 4, mblock: [12, 1], ublock: [4, 1], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xe9e1200], [0, 0xea17240], [0, 0xea4d280]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [3, 1], t: 4, mblock: [12, 1], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: c, relu_en: true, relu_mode: max, relu_threshold: 4, m_k: 13, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, broadcast: {z: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [8, 1], t: 1, mblock: [1, 7], ublock: [10, 15], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x346c6680], [0, 0x34b63ac0], [0, 0x35000f00], [0, 0x3549e340], [0, 0x3593b780], [0, 0x35dd8bc0], [0, 0x36276000], [0, 0x36713440]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [8, 1], t: 8, mblock: [10, 1], ublock: [4, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xdbb30c0], [0, 0xdd1b100], [0, 0xde83140], [0, 0xdfeb180], [0, 0xe1531c0], [0, 0xe2bb200], [0, 0xe423240], [0, 0xe58b280]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [8, 1], t: 8, mblock: [10, 1], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: c, stoch_rnd_mode: none, m_k: 7, u_kt: 15, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
