#Test id=0
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [10, 3], ublock: [2, 5], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2e172f80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 3], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xb1c0100]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 5], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: r, m_k: 5, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 1, mblock: [10, 12], ublock: [12, 3], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3d53a2c0], [0, 0x3e836300]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 1, mblock: [1, 12], ublock: [1, 3], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xfbd8800], [0, 0xfc01040]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 1, mblock: [1, 12], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, m_k: 10, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 30, mblock: [14, 16], ublock: [5, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x293cd900]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 30, mblock: [1, 16], ublock: [1, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xe961440]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 30, mblock: [1, 16], ublock: [1, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 77, m_k: 14, u_kt: 5, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 3], t: 1, mblock: [12, 10], ublock: [3, 2], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x29994680], [0, 0x29a5eec0], [0, 0x29b29700]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 3], t: 4, mblock: [1, 5], ublock: [1, 4], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xedc96c0], [0, 0xeddff00], [0, 0xedf6740]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 3], t: 4, mblock: [1, 5], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 44, m_k: 9, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, broadcast: {z: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 8], t: 1, mblock: [16, 4], ublock: [4, 3], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3a6437c0], [0, 0x3a9a3800], [0, 0x3ad03840], [0, 0x3b063880], [0, 0x3b3c38c0], [0, 0x3b723900], [0, 0x3ba83940], [0, 0x3bde3980]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 8], t: 8, mblock: [1, 3], ublock: [1, 4], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf1ba540], [0, 0xf226580], [0, 0xf2925c0], [0, 0xf2fe600], [0, 0xf36a640], [0, 0xf3d6680], [0, 0xf4426c0], [0, 0xf4ae700]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 8], t: 8, mblock: [1, 3], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: r, m_k: 16, u_kt: 16, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
