#Test id=0
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [2, 1], t: 48, mblock: [14, 1], ublock: [4, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x2eb90740], [0, 0x2f760780]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [2, 1], t: 24, mblock: [14, 6], ublock: [4, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xb47e5c0], [0, 0xd7ee600]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [2, 1], t: 24, mblock: [14, 6], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, accumulate: true, z: 2, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {c: 6}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [2, 2], t: 16, mblock: [3, 2], ublock: [1, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x21e09980], [0, 0x21e759c0], [0, 0x21ee1a00], [0, 0x21f4da40]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [2, 2], t: 1, mblock: [5, 14], ublock: [3, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xfc33f80], [0, 0xfd203c0], [0, 0xfe0c800], [0, 0xfef8c40]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [2, 2], t: 1, mblock: [5, 14], ublock: [3, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, relu_en: true, relu_mode: max, relu_threshold: 94, accumulate: true, z: 16, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 5}, broadcast: {c: 7}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [6, 2], t: 14, mblock: [10, 6], ublock: [4, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x26d4c140], [0, 0x27c10180], [0, 0x28ad41c0], [0, 0x29998200], [0, 0x2a85c240], [0, 0x2b720280], [0, 0x2c5e42c0], [0, 0x2d4a8300], [0, 0x2e36c340], [0, 0x2f230380], [0, 0x300f43c0], [0, 0x30fb8400]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [6, 2], t: 1, mblock: [10, 6], ublock: [4, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xddf0a00], [0, 0xdefea40], [0, 0xe00ca80], [0, 0xe11aac0], [0, 0xe228b00], [0, 0xe336b40], [0, 0xe444b80], [0, 0xe552bc0], [0, 0xe660c00], [0, 0xe76ec40], [0, 0xe87cc80], [0, 0xe98acc0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [6, 2], t: 1, mblock: [10, 6], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, relu_en: true, relu_mode: max, relu_threshold: 40, accumulate: true, z: 14, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [1, 7], t: 1, mblock: [1, 3], ublock: [4, 4], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x12be60c0], [0, 0x12bf3900], [0, 0x12c01140], [0, 0x12c0e980], [0, 0x12c1c1c0], [0, 0x12c29a00], [0, 0x12c37240]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 7], t: 2, mblock: [7, 12], ublock: [4, 1], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xf9c2680], [0, 0xfa7f6c0], [0, 0xfb3c700], [0, 0xfbf9740], [0, 0xfcb6780], [0, 0xfd737c0], [0, 0xfe30800]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 7], t: 2, mblock: [7, 12], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, relu_en: true, relu_mode: max, relu_threshold: 113, accumulate: true, z: 3, stoch_rnd_mode: none, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 7}, broadcast: {z: 6}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [3, 7], t: 1, mblock: [1, 2], ublock: [3, 2], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3677dc00], [0, 0x3678b440], [0, 0x36798c80], [0, 0x367a64c0], [0, 0x367b3d00], [0, 0x367c1540], [0, 0x367ced80], [0, 0x367dc5c0], [0, 0x367e9e00], [0, 0x367f7640], [0, 0x36804e80], [0, 0x368126c0], [0, 0x3681ff00], [0, 0x3682d740], [0, 0x3683af80], [0, 0x368487c0], [0, 0x36856000], [0, 0x36863840], [0, 0x36871080], [0, 0x3687e8c0], [0, 0x3688c100]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [3, 7], t: 2, mblock: [9, 1], ublock: [1, 4], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xdb6ef80], [0, 0xdbbffc0], [0, 0xdc11000], [0, 0xdc62040], [0, 0xdcb3080], [0, 0xdd040c0], [0, 0xdd55100], [0, 0xdda6140], [0, 0xddf7180], [0, 0xde481c0], [0, 0xde99200], [0, 0xdeea240], [0, 0xdf3b280], [0, 0xdf8c2c0], [0, 0xdfdd300], [0, 0xe02e340], [0, 0xe07f380], [0, 0xe0d03c0], [0, 0xe121400], [0, 0xe172440], [0, 0xe1c3480]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [3, 7], t: 2, mblock: [9, 1], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, accumulate: true, z: 4, stoch_rnd_mode: fpu, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 3}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
