- input_dram_buffers: '[[0, 0x10000000],[0, 0x11000000],[0, 0x12000000],[0, 0x13000000],[0,
    0x14000000],[0, 0x15000000],[0, 0x16000000],[0, 0x17000000],[0, 0x18000000],[0,
    0x19000000],[0, 0x1a000000],[0, 0x1b000000],[0, 0x1c000000],[0, 0x1d000000],[0,
    0x1e000000],[0, 0x1f000000],]'
  input_grid_c: 4
  input_grid_r: 4
  input_mb_c: 1
  input_mb_r: 1
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],]'
  output_grid_c: 4
  output_grid_r: 1
  output_mb_c: 1
  output_mb_r: 4
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 8
  tensor_r: 8
- input_dram_buffers: '[[0, 0x10000000],]'
  input_grid_c: 1
  input_grid_r: 1
  input_mb_c: 2
  input_mb_r: 2
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],]'
  output_grid_c: 1
  output_grid_r: 2
  output_mb_c: 2
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 4
- input_dram_buffers: '[[0, 0x10000000],[0, 0x11000000],[0, 0x12000000],[0, 0x13000000],[0,
    0x14000000],[0, 0x15000000],]'
  input_grid_c: 2
  input_grid_r: 3
  input_mb_c: 1
  input_mb_r: 1
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],[1,
    0x14000000],[1, 0x15000000],]'
  output_grid_c: 2
  output_grid_r: 3
  output_mb_c: 1
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 6
- input_dram_buffers: '[[0, 0x10000000],[0, 0x11000000],[0, 0x12000000],]'
  input_grid_c: 3
  input_grid_r: 1
  input_mb_c: 1
  input_mb_r: 3
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],[1,
    0x14000000],[1, 0x15000000],[1, 0x16000000],[1, 0x17000000],[1, 0x18000000],]'
  output_grid_c: 3
  output_grid_r: 3
  output_mb_c: 1
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 6
  tensor_r: 6
- input_dram_buffers: '[[0, 0x10000000],[0, 0x11000000],]'
  input_grid_c: 2
  input_grid_r: 1
  input_mb_c: 1
  input_mb_r: 3
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],[1,
    0x14000000],[1, 0x15000000],]'
  output_grid_c: 2
  output_grid_r: 3
  output_mb_c: 1
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 6
- input_dram_buffers: '[[0, 0x10000000],]'
  input_grid_c: 1
  input_grid_r: 1
  input_mb_c: 2
  input_mb_r: 3
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],[1,
    0x14000000],[1, 0x15000000],]'
  output_grid_c: 2
  output_grid_r: 3
  output_mb_c: 1
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 6
- input_dram_buffers: '[[0, 0x10000000],]'
  input_grid_c: 1
  input_grid_r: 1
  input_mb_c: 2
  input_mb_r: 4
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],[1,
    0x14000000],[1, 0x15000000],[1, 0x16000000],[1, 0x17000000],]'
  output_grid_c: 2
  output_grid_r: 4
  output_mb_c: 1
  output_mb_r: 1
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 8
- input_dram_buffers: '[[0, 0x10000000],]'
  input_grid_c: 1
  input_grid_r: 1
  input_mb_c: 2
  input_mb_r: 4
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],]'
  output_grid_c: 2
  output_grid_r: 1
  output_mb_c: 1
  output_mb_r: 4
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 8
- input_dram_buffers: '[[0, 0x10000000],]'
  input_grid_c: 1
  input_grid_r: 1
  input_mb_c: 2
  input_mb_r: 4
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],]'
  output_grid_c: 2
  output_grid_r: 2
  output_mb_c: 1
  output_mb_r: 2
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 8
- input_dram_buffers: '[[0, 0x10000000],[0, 0x11000000],]'
  input_grid_c: 2
  input_grid_r: 1
  input_mb_c: 1
  input_mb_r: 4
  input_ub_c: 2
  input_ub_r: 2
  output_dram_buffers: '[[1, 0x10000000],[1, 0x11000000],[1, 0x12000000],[1, 0x13000000],]'
  output_grid_c: 2
  output_grid_r: 2
  output_mb_c: 1
  output_mb_r: 2
  output_ub_c: 2
  output_ub_r: 2
  tensor_c: 4
  tensor_r: 8
