#Test id=0
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [12, 2], ublock: [1, 9], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x289d2dc0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 8, mblock: [2, 2], ublock: [1, 2], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x37391ec0]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [1, 1], t: 1, mblock: [2, 1], ublock: [6, 4], df: Int32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x391e1380]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 4, mblock: [12, 1], ublock: [1, 4], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf89dac0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [1, 1], t: 4, mblock: [12, 1], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1, input_2], in_df: [Int8, Int8, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {accumulate: true, z: 2, stoch_rnd_mode: fpu, bias: true, m_k: 9, u_kt: 2, kernel_broadcast_per_t : {input_1 : 40}, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {z: 8}, ], input_1_tms: [broadcast: {r: 9}, ], input_2_tms: [broadcast: {z: 4}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.4, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [2, 5], t: 28, mblock: [1, 9], ublock: [1, 2], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x12048640], [0, 0x120d6280], [0, 0x12163ec0], [0, 0x121f1b00], [0, 0x1227f740], [0, 0x1230d380], [0, 0x1239afc0], [0, 0x12428c00], [0, 0x124b6840], [0, 0x12544480]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [2, 5], t: 28, mblock: [1, 1], ublock: [5, 10], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x232b1800], [0, 0x2343b440], [0, 0x235c5080], [0, 0x2374ecc0], [0, 0x238d8900], [0, 0x23a62540], [0, 0x23bec180], [0, 0x23d75dc0], [0, 0x23effa00], [0, 0x24089640]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [2, 5], t: 1, mblock: [3, 5], ublock: [2, 2], df: Int32, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0x550d200], [0, 0x554a140], [0, 0x5587080], [0, 0x55c3fc0], [0, 0x5600f00], [0, 0x563de40], [0, 0x567ad80], [0, 0x56b7cc0], [0, 0x56f4c00], [0, 0x5731b40]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [2, 5], t: 1, mblock: [3, 5], ublock: [2, 2], out_df: Int32, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {accumulate: true, z: 28, m_k: 10, u_kt: 9, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 6}, ], input_1_tms: [broadcast: {r: 9}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0, check_pcc: 0.8, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [5, 5], t: 1, mblock: [7, 3], ublock: [4, 4], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3bc8e340], [0, 0x3bcecb80], [0, 0x3bd4b3c0], [0, 0x3bda9c00], [0, 0x3be08440], [0, 0x3be66c80], [0, 0x3bec54c0], [0, 0x3bf23d00], [0, 0x3bf82540], [0, 0x3bfe0d80], [0, 0x3c03f5c0], [0, 0x3c09de00], [0, 0x3c0fc640], [0, 0x3c15ae80], [0, 0x3c1b96c0], [0, 0x3c217f00], [0, 0x3c276740], [0, 0x3c2d4f80], [0, 0x3c3337c0], [0, 0x3c392000], [0, 0x3c3f0840], [0, 0x3c44f080], [0, 0x3c4ad8c0], [0, 0x3c50c100], [0, 0x3c56a940]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [5, 5], t: 1, mblock: [2, 2], ublock: [1, 1], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3c6a7300], [0, 0x3c6a8540], [0, 0x3c6a9780], [0, 0x3c6aa9c0], [0, 0x3c6abc00], [0, 0x3c6ace40], [0, 0x3c6ae080], [0, 0x3c6af2c0], [0, 0x3c6b0500], [0, 0x3c6b1740], [0, 0x3c6b2980], [0, 0x3c6b3bc0], [0, 0x3c6b4e00], [0, 0x3c6b6040], [0, 0x3c6b7280], [0, 0x3c6b84c0], [0, 0x3c6b9700], [0, 0x3c6ba940], [0, 0x3c6bbb80], [0, 0x3c6bcdc0], [0, 0x3c6be000], [0, 0x3c6bf240], [0, 0x3c6c0480], [0, 0x3c6c16c0], [0, 0x3c6c2900]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [5, 5], t: 1, mblock: [14, 1], ublock: [2, 2], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3c6d1d80], [0, 0x3c70abc0], [0, 0x3c743a00], [0, 0x3c77c840], [0, 0x3c7b5680], [0, 0x3c7ee4c0], [0, 0x3c827300], [0, 0x3c860140], [0, 0x3c898f80], [0, 0x3c8d1dc0], [0, 0x3c90ac00], [0, 0x3c943a40], [0, 0x3c97c880], [0, 0x3c9b56c0], [0, 0x3c9ee500], [0, 0x3ca27340], [0, 0x3ca60180], [0, 0x3ca98fc0], [0, 0x3cad1e00], [0, 0x3cb0ac40], [0, 0x3cb43a80], [0, 0x3cb7c8c0], [0, 0x3cbb5700], [0, 0x3cbee540], [0, 0x3cc27380]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: 'input_3: {type: queue, grid_size: [5, 5], t: 4, mblock: [7, 2], ublock: [4, 1], df: Float32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x3d1fd980], [0, 0x3d2e11c0], [0, 0x3d3c4a00], [0, 0x3d4a8240], [0, 0x3d58ba80], [0, 0x3d66f2c0], [0, 0x3d752b00], [0, 0x3d836340], [0, 0x3d919b80], [0, 0x3d9fd3c0], [0, 0x3dae0c00], [0, 0x3dbc4440], [0, 0x3dca7c80], [0, 0x3dd8b4c0], [0, 0x3de6ed00], [0, 0x3df52540], [0, 0x3e035d80], [0, 0x3e1195c0], [0, 0x3e1fce00], [0, 0x3e2e0640], [0, 0x3e3c3e80], [0, 0x3e4a76c0], [0, 0x3e58af00], [0, 0x3e66e740], [0, 0x3e751f80]], }'
  stimulus_in3: 'input_3: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in3: 'input_3: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  out0: 'output0: {type: queue, grid_size: [5, 5], t: 4, mblock: [14, 2], ublock: [4, 1], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xf0f8f00], [0, 0xf176f40], [0, 0xf1f4f80], [0, 0xf272fc0], [0, 0xf2f1000], [0, 0xf36f040], [0, 0xf3ed080], [0, 0xf46b0c0], [0, 0xf4e9100], [0, 0xf567140], [0, 0xf5e5180], [0, 0xf6631c0], [0, 0xf6e1200], [0, 0xf75f240], [0, 0xf7dd280], [0, 0xf85b2c0], [0, 0xf8d9300], [0, 0xf957340], [0, 0xf9d5380], [0, 0xfa533c0], [0, 0xfad1400], [0, 0xfb4f440], [0, 0xfbcd480], [0, 0xfc4b4c0], [0, 0xfcc9500]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [5, 5], t: 4, mblock: [14, 2], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1, input_2, input_3], in_df: [Int8, Int8, Int32, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {requant: true, dequant: false, zero_point: 91, accumulate: true, z: 2, bias: true, m_k: 60, u_kt: 1, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, broadcast: {z: 8}, ], input_1_tms: [broadcast: {r: 6}, broadcast: {z: 8}, ], input_2_tms: [broadcast: {r: 2}, broadcast: {z: 4}, ], input_3_tms: [broadcast: {r: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0, check_pcc: 0.8, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 44, mblock: [16, 6], ublock: [2, 4], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x34dbf280]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [1, 1], t: 44, mblock: [6, 3], ublock: [4, 1], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x3ecc8880]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 2, mblock: [16, 3], ublock: [2, 1], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xf734440]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [1, 1], t: 2, mblock: [16, 3], ublock: [2, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1], in_df: [Int8, Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {accumulate: true, z: 22, stoch_rnd_mode: none, m_k: 6, u_kt: 4, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], input_1_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0, check_pcc: 0.8, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: BLACKHOLE
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [7, 1], t: 1, mblock: [1, 1], ublock: [1, 14], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x162eef00], [0, 0x162feb40], [0, 0x1630e780], [0, 0x1631e3c0], [0, 0x1632e000], [0, 0x1633dc40], [0, 0x1634d880]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [7, 1], t: 1, mblock: [1, 2], ublock: [1, 15], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x16d4bec0], [0, 0x16d6db00], [0, 0x16d8f740], [0, 0x16db1380], [0, 0x16dd2fc0], [0, 0x16df4c00], [0, 0x16e16840]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [7, 1], t: 1, mblock: [1, 10], ublock: [2, 3], df: Int32, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x17021d80], [0, 0x171159c0], [0, 0x17209600], [0, 0x172fd240], [0, 0x173f0e80], [0, 0x174e4ac0], [0, 0x175d8700]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [7, 1], t: 1, mblock: [4, 15], ublock: [1, 2], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xb249b80], [0, 0xb2d0bc0], [0, 0xb357c00], [0, 0xb3dec40], [0, 0xb465c80], [0, 0xb4eccc0], [0, 0xb573d00]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [7, 1], t: 1, mblock: [4, 15], ublock: [1, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1, input_2], in_df: [Int8, Int8, Int32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {accumulate: true, z: 2, bias: true, m_k: 7, u_kt: 2, sfpu_op: gelu, sfpu_execution_thread: pack, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 4}, broadcast: {z: 2}, ], input_1_tms: [broadcast: {r: 2}, broadcast: {z: 2}, ], input_2_tms: [broadcast: {r: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0.4, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=5
- device: BLACKHOLE
  loop_count: 1
  input_count: 1
  target_device: 0
  queue_wrap_size: 2
  in0: 'input_0: {type: queue, grid_size: [4, 4], t: 1, mblock: [1, 5], ublock: [1, 14], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x2494f0c0], [0, 0x24962c00], [0, 0x24976740], [0, 0x2498a280], [0, 0x2499ddc0], [0, 0x249b1900], [0, 0x249c5440], [0, 0x249d8f80], [0, 0x249ecac0], [0, 0x24a00600], [0, 0x24a14140], [0, 0x24a27c80], [0, 0x24a3b7c0], [0, 0x24a4f300], [0, 0x24a62e40], [0, 0x24a76980]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: 'input_1: {type: queue, grid_size: [4, 4], t: 6, mblock: [1, 4], ublock: [14, 2], df: Int8, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x250f9440], [0, 0x251b6480], [0, 0x252734c0], [0, 0x25330500], [0, 0x253ed540], [0, 0x254aa580], [0, 0x255675c0], [0, 0x25624600], [0, 0x256e1640], [0, 0x2579e680], [0, 0x2585b6c0], [0, 0x25918700], [0, 0x259d5740], [0, 0x25a92780], [0, 0x25b4f7c0], [0, 0x25c0c800]], }'
  stimulus_in1: 'input_1: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in1: 'input_1: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in2: 'input_2: {type: queue, grid_size: [4, 4], t: 1, mblock: [1, 1], ublock: [1, 8], df: Int32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x2e09b8c0], [0, 0x2e0a3b00], [0, 0x2e0abd40], [0, 0x2e0b3f80], [0, 0x2e0bc1c0], [0, 0x2e0c4400], [0, 0x2e0cc640], [0, 0x2e0d4880], [0, 0x2e0dcac0], [0, 0x2e0e4d00], [0, 0x2e0ecf40], [0, 0x2e0f5180], [0, 0x2e0fd3c0], [0, 0x2e105600], [0, 0x2e10d840], [0, 0x2e115a80]], }'
  stimulus_in2: 'input_2: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in2: 'input_2: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in3: 'input_3: {type: queue, grid_size: [4, 4], t: 1, mblock: [3, 4], ublock: [1, 2], df: Float32, input: HOST, entries: 1, target_device: 0, loc: dram, dram: [[0, 0x2edd5b80], [0, 0x2edee1c0], [0, 0x2ee06800], [0, 0x2ee1ee40], [0, 0x2ee37480], [0, 0x2ee4fac0], [0, 0x2ee68100], [0, 0x2ee80740], [0, 0x2ee98d80], [0, 0x2eeb13c0], [0, 0x2eec9a00], [0, 0x2eee2040], [0, 0x2eefa680], [0, 0x2ef12cc0], [0, 0x2ef2b300], [0, 0x2ef43940]], }'
  stimulus_in3: 'input_3: {type: Uniform, uniform_lower_bound: -2.0, uniform_upper_bound: 2.0}'
  queue_settings_in3: 'input_3: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  out0: 'output0: {type: queue, grid_size: [4, 4], t: 2, mblock: [9, 2], ublock: [1, 4], df: Int8, input: op, entries: 1, target_device: 0, loc: host, host: [[0, 0xf6b0fc0], [0, 0xf6d9800], [0, 0xf702040], [0, 0xf72a880], [0, 0xf7530c0], [0, 0xf77b900], [0, 0xf7a4140], [0, 0xf7cc980], [0, 0xf7f51c0], [0, 0xf81da00], [0, 0xf846240], [0, 0xf86ea80], [0, 0xf8972c0], [0, 0xf8bfb00], [0, 0xf8e8340], [0, 0xf910b80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: matmul, grid_size: [4, 4], t: 2, mblock: [9, 2], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0, input_1, input_2, input_3], in_df: [Int8, Int8, Int32, Float32], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {requant: true, dequant: false, zero_point: 30, accumulate: true, z: 3, bias: true, m_k: 56, u_kt: 5, min_buffer_input: 0, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 9}, broadcast: {z: 6}, ], input_1_tms: [broadcast: {r: 5}, ], input_2_tms: [broadcast: {r: 9}, broadcast: {z: 2}, ], input_3_tms: [broadcast: {r: 3}, broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllClose, atol: 0.01, rtol: 0.15, check_pct: 0, check_pcc: 0.8, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
