#Test id=0
- device: WORMHOLE_B0
  loop_count: 2
  input_count: 6
  target_device: 0
  queue_wrap_size: 24
  in0: 'input_0: {type: queue, grid_size: [3, 1], t: 6, mblock: [7, 12], ublock: [4, 1], df: Int8, input: HOST, entries: 12, target_device: 0, loc: dram, dram: [[0, 0x1d67b800], [0, 0x20ba3820], [0, 0x240cb840]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [3, 1], t: 1, mblock: [7, 12], ublock: [4, 1], df: Int8, input: op, entries: 12, target_device: 0, loc: host, host: [[0, 0xd9d3040], [0, 0xe2af060], [0, 0xeb8b080]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [3, 1], t: 1, mblock: [7, 12], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, accumulate: true, z: 6, stoch_rnd_mode: none, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 16
  target_device: 0
  queue_wrap_size: 32
  in0: 'input_0: {type: queue, grid_size: [6, 3], t: 4, mblock: [1, 7], ublock: [2, 4], df: Int8, input: HOST, entries: 16, target_device: 0, loc: dram, dram: [[0, 0x2b543d40], [0, 0x2b933d60], [0, 0x2bd23d80], [0, 0x2c113da0], [0, 0x2c503dc0], [0, 0x2c8f3de0], [0, 0x2cce3e00], [0, 0x2d0d3e20], [0, 0x2d4c3e40], [0, 0x2d8b3e60], [0, 0x2dca3e80], [0, 0x2e093ea0], [0, 0x2e483ec0], [0, 0x2e873ee0], [0, 0x2ec63f00], [0, 0x2f053f20], [0, 0x2f443f40], [0, 0x2f833f60]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [6, 3], t: 1, mblock: [14, 14], ublock: [1, 2], df: Int8, input: op, entries: 16, target_device: 0, loc: host, host: [[0, 0x6cd3fc0], [0, 0x73b7fe0], [0, 0x7a9c000], [0, 0x8180020], [0, 0x8864040], [0, 0x8f48060], [0, 0x962c080], [0, 0x9d100a0], [0, 0xa3f40c0], [0, 0xaad80e0], [0, 0xb1bc100], [0, 0xb8a0120], [0, 0xbf84140], [0, 0xc668160], [0, 0xcd4c180], [0, 0xd4301a0], [0, 0xdb141c0], [0, 0xe1f81e0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [6, 3], t: 1, mblock: [14, 14], ublock: [1, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, accumulate: true, z: 4, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 7}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: WORMHOLE_B0
  loop_count: 2
  input_count: 10
  target_device: 0
  queue_wrap_size: 40
  in0: 'input_0: {type: queue, grid_size: [5, 6], t: 2, mblock: [2, 1], ublock: [1, 9], df: Int8, input: HOST, entries: 20, target_device: 0, loc: dram, dram: [[0, 0x2142ac40], [0, 0x215bfc60], [0, 0x21754c80], [0, 0x218e9ca0], [0, 0x21a7ecc0], [0, 0x21c13ce0], [0, 0x21da8d00], [0, 0x21f3dd20], [0, 0x220d2d40], [0, 0x22267d60], [0, 0x223fcd80], [0, 0x22591da0], [0, 0x22726dc0], [0, 0x228bbde0], [0, 0x22a50e00], [0, 0x22be5e20], [0, 0x22d7ae40], [0, 0x22f0fe60], [0, 0x230a4e80], [0, 0x23239ea0], [0, 0x233ceec0], [0, 0x23563ee0], [0, 0x236f8f00], [0, 0x2388df20], [0, 0x23a22f40], [0, 0x23bb7f60], [0, 0x23d4cf80], [0, 0x23ee1fa0], [0, 0x24076fc0], [0, 0x2420bfe0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [5, 6], t: 1, mblock: [12, 3], ublock: [1, 3], df: Int8, input: op, entries: 20, target_device: 0, loc: host, host: [[0, 0x670ecc0], [0, 0x6bcdce0], [0, 0x708cd00], [0, 0x754bd20], [0, 0x7a0ad40], [0, 0x7ec9d60], [0, 0x8388d80], [0, 0x8847da0], [0, 0x8d06dc0], [0, 0x91c5de0], [0, 0x9684e00], [0, 0x9b43e20], [0, 0xa002e40], [0, 0xa4c1e60], [0, 0xa980e80], [0, 0xae3fea0], [0, 0xb2feec0], [0, 0xb7bdee0], [0, 0xbc7cf00], [0, 0xc13bf20], [0, 0xc5faf40], [0, 0xcab9f60], [0, 0xcf78f80], [0, 0xd437fa0], [0, 0xd8f6fc0], [0, 0xddb5fe0], [0, 0xe275000], [0, 0xe734020], [0, 0xebf3040], [0, 0xf0b2060]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [5, 6], t: 1, mblock: [12, 3], ublock: [1, 3], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, relu_en: true, relu_mode: max, relu_threshold: 88, accumulate: true, z: 2, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 6}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 14
  target_device: 0
  queue_wrap_size: 28
  in0: 'input_0: {type: queue, grid_size: [5, 3], t: 1, mblock: [3, 2], ublock: [1, 7], df: Int8, input: HOST, entries: 14, target_device: 0, loc: dram, dram: [[0, 0x2ab9f940], [0, 0x2ac44f60], [0, 0x2acea580], [0, 0x2ad8fba0], [0, 0x2ae351c0], [0, 0x2aeda7e0], [0, 0x2af7fe00], [0, 0x2b025420], [0, 0x2b0caa40], [0, 0x2b170060], [0, 0x2b215680], [0, 0x2b2baca0], [0, 0x2b3602c0], [0, 0x2b4058e0], [0, 0x2b4aaf00]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [5, 3], t: 1, mblock: [6, 14], ublock: [4, 1], df: Int8, input: op, entries: 14, target_device: 0, loc: host, host: [[0, 0xaa12540], [0, 0xaf3d560], [0, 0xb468580], [0, 0xb9935a0], [0, 0xbebe5c0], [0, 0xc3e95e0], [0, 0xc914600], [0, 0xce3f620], [0, 0xd36a640], [0, 0xd895660], [0, 0xddc0680], [0, 0xe2eb6a0], [0, 0xe8166c0], [0, 0xed416e0], [0, 0xf26c700]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [5, 3], t: 1, mblock: [6, 14], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, accumulate: true, z: 2, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 12
  target_device: 0
  queue_wrap_size: 24
  in0: 'input_0: {type: queue, grid_size: [4, 2], t: 1, mblock: [2, 1], ublock: [1, 5], df: Int8, input: HOST, entries: 12, target_device: 0, loc: dram, dram: [[0, 0x3bf49000], [0, 0x3bf6ac20], [0, 0x3bf8c840], [0, 0x3bfae460], [0, 0x3bfd0080], [0, 0x3bff1ca0], [0, 0x3c0138c0], [0, 0x3c0354e0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [4, 2], t: 1, mblock: [1, 5], ublock: [4, 1], df: Int8, input: op, entries: 12, target_device: 0, loc: host, host: [[0, 0xf1adf40], [0, 0xf1f1760], [0, 0xf234f80], [0, 0xf2787a0], [0, 0xf2bbfc0], [0, 0xf2ff7e0], [0, 0xf343000], [0, 0xf386820]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [4, 2], t: 1, mblock: [1, 5], ublock: [4, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: z, relu_en: true, relu_mode: max, relu_threshold: 49, accumulate: true, z: 2, stoch_rnd_mode: none, m_k: 1, u_kt: 1, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 2}, broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
