#Test id=0
- device: WORMHOLE_B0
  loop_count: 2
  input_count: 1
  target_device: 0
  queue_wrap_size: 4
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 18, mblock: [13, 10], ublock: [6, 4], df: Int8, input: HOST, entries: 2, target_device: 0, loc: dram, dram: [[0, 0x1c81a500]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 18, mblock: [1, 10], ublock: [1, 4], df: Int8, input: op, entries: 2, target_device: 0, loc: host, host: [[0, 0xfc47e40]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 18, mblock: [1, 10], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, m_k: 13, u_kt: 6, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=1
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 4
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 5], t: 36, mblock: [16, 2], ublock: [1, 4], df: Int8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2c3cdb40], [0, 0x2d80db60], [0, 0x2ec4db80], [0, 0x3008dba0], [0, 0x314cdbc0]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 5], t: 36, mblock: [1, 4], ublock: [1, 2], df: Int8, input: op, entries: 4, target_device: 0, loc: host, host: [[0, 0xa418800], [0, 0xa55c820], [0, 0xa6a0840], [0, 0xa7e4860], [0, 0xa928880]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 5], t: 36, mblock: [1, 4], ublock: [1, 2], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, stoch_rnd_mode: fpu, m_k: 8, u_kt: 14, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 7}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=2
- device: WORMHOLE_B0
  loop_count: 2
  input_count: 12
  target_device: 0
  queue_wrap_size: 48
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [4, 1], ublock: [6, 10], df: Int8, input: HOST, entries: 24, target_device: 0, loc: dram, dram: [[0, 0x2c100d80]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 1, mblock: [1, 10], ublock: [1, 1], df: Int8, input: op, entries: 24, target_device: 0, loc: host, host: [[0, 0xd399c80]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 1, mblock: [1, 10], ublock: [1, 1], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 14, m_k: 16, u_kt: 12, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=3
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 4
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 1], t: 1, mblock: [6, 4], ublock: [3, 15], df: Int8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x2fbd6b00]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 1], t: 8, mblock: [1, 15], ublock: [1, 4], df: Int8, input: op, entries: 4, target_device: 0, loc: host, host: [[0, 0xc51d9c0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 1], t: 8, mblock: [1, 15], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int8, acc_df: Int32, attributes: {type: max, dim: r, stoch_rnd_mode: none, m_k: 14, u_kt: 9, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 7}, broadcast: {z: 8}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
#Test id=4
- device: WORMHOLE_B0
  loop_count: 1
  input_count: 4
  target_device: 0
  queue_wrap_size: 8
  in0: 'input_0: {type: queue, grid_size: [1, 2], t: 1, mblock: [7, 8], ublock: [2, 8], df: Int8, input: HOST, entries: 4, target_device: 0, loc: dram, dram: [[0, 0x22bed540], [0, 0x22fdd560]], }'
  stimulus_in0: 'input_0: {type: Uniform, uniform_lower_bound: -10.0, uniform_upper_bound: 10.0}'
  queue_settings_in0: 'input_0: {prologue: false, epilogue: false, zero: false, rd_ptr_local: $lptr, rd_ptr_global: $gptr},'
  in1: ''
  stimulus_in1: ''
  queue_settings_in1: ''
  in2: ''
  stimulus_in2: ''
  queue_settings_in2: ''
  in3: ''
  stimulus_in3: ''
  queue_settings_in3: ''
  out0: 'output0: {type: queue, grid_size: [1, 2], t: 2, mblock: [1, 16], ublock: [1, 4], df: Int8, input: op, entries: 4, target_device: 0, loc: host, host: [[0, 0x8d3d480], [0, 0x8dcd4a0]], }'
  queue_settings_out0: ''
  op0: 'op: {type: reduce, grid_size: [1, 2], t: 2, mblock: [1, 16], ublock: [1, 4], out_df: Int8, grid_loc: [0, 0], inputs: [input_0], in_df: [Int8], math_fidelity: HiFi4, intermed_df: Int32, acc_df: Int32, attributes: {type: max, dim: r, relu_en: true, relu_mode: max, relu_threshold: 102, m_k: 14, u_kt: 8, }, ublock_order: r, buf_size_mb: 2, untilize_output: false, gradient_op: false, input_0_tms: [broadcast: {r: 8}, broadcast: {z: 2}, ], }'
  op1: ''
  op2: ''
  op3: ''
  op4: ''
  op5: ''
  comparison_config: '{type: AllCloseHw, atol: 0.01, rtol: 0.15, check_pct: 0.9, check_pcc: 0.99, verbosity: Concise, check_tile_rows_range: [1, 32], check_tile_cols_range: [1, 32] }'
